### ISSUE TITLE
Turicreate 5.0b1 should use GPU for final layer fine tuning

### ISSUE THREAD

**Issue by mdenty** [apple/turicreate#639] opened 2018-06-08 09:43 UTC
**Edit**: confused by https://github.com/apple/turicreate/issues/635, may be related.
 
I'm running a training on an iMac late-2013 running Mojave beta1.
I'm seeing 4 CPU cores at 100%, but GPU is doing nothing.
I've specified : `tc.config.set_num_gpus(-1)`

Did I missed something ?

The attached screenshot to show what I mean.
![image](https://user-images.githubusercontent.com/10026688/41151438-080e7090-6b11-11e8-838f-857adfd40c6d.png)

**Comment by gustavla** [comment] 2018-06-08 14:53
@mdenty  Thanks for trying it out! Sorry, you are not seeing GPU utilization.

Is this your iMac: https://support.apple.com/kb/sp688?locale=en_US ?

If so, the reason why you are not seeing GPU acceleration is because the graphics card is NVIDIA and  not AMD (as in more recent Macs). Not to worry though, since we also have support for NVIDIA graphics cards.

There are a few more steps to set this up however. First, make sure you have CUDA installed, for instance CUDA 8. Optionally install cuDNN as well, which will lead to greater performance. Finally, uninstall MXNet (`pip uninstall mxnet`) and install the CUDA-enabled MXnet (corresponding to your CUDA version):
```
pip install mxnet-cu80==1.1.0
```
More information can be found here:

https://github.com/apple/turicreate/blob/master/LinuxGPU.md

These instructions assume that you are on Linux, since that's the OS of most of our CUDA users. Right now we do not have any instructions for how to set up CUDA on Mac (and I'm being  vague in my instructions simply because I have not gone through these steps myself). We should add this, so any feedback or tips you have in setting this up, we'd love to hear. Thanks!

**Comment by xvolks** [comment] 2018-06-08 14:59
@gustavla You're right about the iMac model, it's the low end machine with only 1GB of GPU RAM.
I've installed Mojave on this spare computer to avoid issues on production machines. I've no spare machine with AMD card and since Mojave cannot be installed on external usb disk...

**Comment by gustavla** [comment] 2018-06-08 15:06
Note that NVIDIA support does not require Mojave (only AMD support). As long as you have CUDA and `mxnet-cu80`, GPU is supported (on Turi Create 4 as well). 1 GB should be enough to use the image classifier (although turn `batch_size` down if you run into memory issues). The object detector with default settings will require more than 1 GB, so if you are interested in ever trying that model, it may be tricky to use the GPU, but we can try (with some configuring).

**Comment by mdenty** [comment] 2018-06-08 16:20
mxnet-cu80 does not seem to be available under macOS:

`$ ./pip install mxnet-cu80==1.1.0

Collecting mxnet-cu80==1.1.0

  Could not find a version that satisfies the requirement mxnet-cu80==1.1.0 (from versions: )
No matching distribution found for mxnet-cu80==1.1.0`

**Comment by gustavla** [comment] 2018-06-08 16:27
@mdenty You are right. That is really unfortunate. It makes the setup even trickier (but not impossible).

Currently the only solution is to try to install MXNet from source yourself:
https://mxnet.incubator.apache.org/install/osx_setup.html

You can check back here to see if they ever offer pre-built wheels from Mac+CUDA:
http://mxnet.incubator.apache.org/install/index.html?device=MacOS&language=Python&processor=GPU

**Comment by srikris** [comment] 2018-06-08 17:46
@mdenty @gustavla The GPU is not being utilized for that because the last layer fine tuning happens on the GPU. All the expensive feature extraction is being done in the GPU but the final layer retraining is done in the CPU. This is usually not an issue unless you have a large number of classes.

I'm re-titling to use the GPU for the final layer fine tuning.

**Comment by rainhut** [comment] 2018-07-20 07:07
What is the projection for GPU Style Transfer? I'm writing articles about Turicreate on Medium. 
[https://medium.com/datadriveninvestor/turicreate-style-transfer-that-works-13b9774c70b1](url)

**Comment by rainhut** [comment] 2018-07-20 07:08
What is the projection for GPU Style Transfer? I'm writing articles about Turicreate on Medium. 
[https://medium.com/datadriveninvestor/turicreate-style-transfer-that-works-13b9774c70b1](url)

**Comment by TobyRoseman** [comment] 2020-09-01 22:34
This is a duplicate of #1077.

**Closed by TobyRoseman** 2020-09-01 22:34 UTC
Labels: enhancement, performance, toolkits
