### ISSUE TITLE
VNCoreMLRequest with GPU utilization conflicts with Metal while deployment on IOS 11.4.1 

### ISSUE THREAD

**Issue by foxen** [apple/turicreate#1036] opened 2018-08-24 09:46 UTC
Hello! 
It's looks like related to [#307](https://github.com/apple/turicreate/issues/307)
If I try use GPU for classification request like:
`request.usesCPUOnly = false`
and just declare SCNScene and even not init it, app on iPhone SE with IOS 11.4.1 fails with:

validateComputeFunctionArguments:852: failed assertion `Compute Function(TARR_elementwise_mul_f16_pack4): The pixel format (MTLPixelFormatRGBA32Float) of the texture (name:<null>) bound at index 2 is incompatible with the data type (MTLDataTypeHalf) of the texture parameter (src_b [[texture(0)]]). MTLPixelFormatRGBA32Float is compatible with the data type(s) (
    float
).'

**Comment by nickjong** [comment] 2018-08-24 19:55
This looks like a dupe of #146, which appears to be a framework bug that shipped with macOS 10.13 and iOS 11. From that issue, the workaround seems to be to disable Metal API validation (essentially disabling some runtime assertions). (https://github.com/apple/turicreate/issues/146#issuecomment-370189366) Does that work for you?

**Comment by znation** [comment] 2018-08-24 20:12
This is a dupe of #146. Closing.

**Comment by foxen** [comment] 2018-08-24 20:12
@nickjong Yes, It does work. Thank you!

**Closed by znation** 2018-08-24 20:12 UTC
