### ISSUE TITLE
Configure fails for want of numpy (Linux system has it via its own package manager)

### ISSUE THREAD

**Issue by MincingWords** [apple/turicreate#562] opened 2018-04-30 22:16 UTC
Just downloaded the current tree (as of Apr 30 2018) and attempted configure. List of req'ts met per BUILD.md; the system has virtualenv, blas, lapack, nodejs. Here is the ./configure output, performed on Gentoo Linux: 

> msba01 /opt/turicreate-master/current # ./configure
> Installing python toolchain.
> python version = python2.7.
> /opt/turicreate-master/current /opt/turicreate-master/current
> + set -e
> + [[ -z '' ]]
> + VIRTUALENV=virtualenv
> + PIP=pip3
> + PYTHON_FULL_NAME=python2.7m
> + [[ python2.7 == \p\y\t\h\o\n\2\.\7 ]]
> + PIP=pip
> + PYTHON_FULL_NAME=python2.7
> + virtualenv /opt/turicreate-master/current/deps/env
> Using base prefix '/usr'
> New python executable in /opt/turicreate-master/current/deps/env/bin/python3.6
> Also creating executable in /opt/turicreate-master/current/deps/env/bin/python
> Installing setuptools, pip, wheel...done.
> + source /opt/turicreate-master/current/deps/env/bin/activate
> ++ deactivate nondestructive
> ++ unset -f pydoc
> ++ '[' -z '' ']'
> ++ '[' -z '' ']'
> ++ '[' -n /bin/bash ']'
> ++ hash -r
> ++ '[' -z '' ']'
> ++ unset VIRTUAL_ENV
> ++ '[' '!' nondestructive = nondestructive ']'
> ++ VIRTUAL_ENV=/opt/turicreate-master/current/deps/env
> ++ export VIRTUAL_ENV
> ++ _OLD_VIRTUAL_PATH=/sbin:/bin:/usr/sbin:/usr/bin
> ++ PATH=/opt/turicreate-master/current/deps/env/bin:/sbin:/bin:/usr/sbin:/usr/bin
> ++ export PATH
> ++ '[' -z '' ']'
> ++ '[' -z '' ']'
> ++ _OLD_VIRTUAL_PS1=
> ++ '[' x '!=' x ']'
> +++ basename /opt/turicreate-master/current/deps/env
> ++ PS1='(env) '
> ++ export PS1
> ++ alias pydoc
> ++ '[' -n /bin/bash ']'
> ++ hash -r
> + python_scripts=deps/env/bin
> + deps/env/bin/pip install --upgrade 'pip>=8.1'
> Requirement already up-to-date: pip>=8.1 in ./deps/env/lib/python3.6/site-packages (10.0.1)
> + deps/env/bin/pip install -r scripts/requirements.txt
> Collecting coremltools==0.8 (from -r scripts/requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/8f/ab/b4dea5ab2503f3e601052958985153cd41bd4f9a336fb74f6789151d976e/coremltools-0.8-py3.5-none-manylinux1_x86_64.whl
> Collecting scipy==0.19.1 (from -r scripts/requirements.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/0e/46/da8d7166102d29695330f7c0b912955498542988542c0d2ae3ea0389c68d/scipy-0.19.1-cp36-cp36m-manylinux1_x86_64.whl
> Collecting numpy==1.11.1 (from -r scripts/requirements.txt (line 3))
> Collecting cython==0.24 (from -r scripts/requirements.txt (line 4))
> Collecting Jinja2==2.8 (from -r scripts/requirements.txt (line 5))
>   Using cached https://files.pythonhosted.org/packages/96/a1/c56bc4d99dc2663514a8481511e80eba8994133ae75eebdadfc91a5597d9/Jinja2-2.8-py2.py3-none-any.whl
> Collecting argparse==1.2.1 (from -r scripts/requirements.txt (line 6))
> Collecting decorator==4.1.2 (from -r scripts/requirements.txt (line 7))
>   Using cached https://files.pythonhosted.org/packages/a1/4e/c42167ba5c3192bed633726d39d7896cc55d4fa3ec4a1fb60cd3a53fc4c7/decorator-4.1.2-py2.py3-none-any.whl
> Collecting mock==2.0.0 (from -r scripts/requirements.txt (line 8))
>   Using cached https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl
> Collecting pytest==3.2.5 (from -r scripts/requirements.txt (line 9))
>   Using cached https://files.pythonhosted.org/packages/ef/41/d8a61f1b2ba308e96b36106e95024977e30129355fd12087f23e4b9852a1/pytest-3.2.5-py2.py3-none-any.whl
> Collecting pandas==0.22.0 (from -r scripts/requirements.txt (line 10))
>   Using cached https://files.pythonhosted.org/packages/da/c6/0936bc5814b429fddb5d6252566fe73a3e40372e6ceaf87de3dec1326f28/pandas-0.22.0-cp36-cp36m-manylinux1_x86_64.whl
> Collecting pillow==5.0.0 (from -r scripts/requirements.txt (line 11))
>   Using cached https://files.pythonhosted.org/packages/9a/2f/86941111d108fd060190c994f15881283b98693c1c370e74885cfc470eb3/Pillow-5.0.0-cp36-cp36m-manylinux1_x86_64.whl
> Collecting prettytable==0.7.2 (from -r scripts/requirements.txt (line 12))
> Collecting pytz==2016.3 (from -r scripts/requirements.txt (line 13))
>   Using cached https://files.pythonhosted.org/packages/e2/87/e774b15dd6468889e5268ebbc00040c9f9da546c462099c4d43e14697e04/pytz-2016.3-py2.py3-none-any.whl
> Collecting requests>=2.9.1 (from -r scripts/requirements.txt (line 14))
>   Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
> Collecting scikit-learn==0.17.1 (from -r scripts/requirements.txt (line 15))
>   Using cached https://files.pythonhosted.org/packages/0d/1d/9c775f9403565f68aa23f9cef76c817a7115abd7ca1e1c5958a68c49fb6f/scikit-learn-0.17.1.tar.gz
> Collecting six==1.10.0 (from -r scripts/requirements.txt (line 16))
>   Using cached https://files.pythonhosted.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
> Collecting statsmodels==0.8.0 (from -r scripts/requirements.txt (line 17))
>   Using cached https://files.pythonhosted.org/packages/0d/e9/70d80b48c8c52a8de3ec7cd50e2aa2b1f3cf3f95e42b15fdcb59bd7189f3/statsmodels-0.8.0-cp36-cp36m-manylinux1_x86_64.whl
> Collecting wheel==0.29.0 (from -r scripts/requirements.txt (line 18))
>   Using cached https://files.pythonhosted.org/packages/8a/e9/8468cd68b582b06ef554be0b96b59f59779627131aad48f8a5bce4b13450/wheel-0.29.0-py2.py3-none-any.whl
> Collecting mxnet==0.11 (from -r scripts/requirements.txt (line 19))
>   Using cached https://files.pythonhosted.org/packages/d7/1d/af82e37a65250c03ddfb89f5c096d673c167c9ee8122d219f0d7d4492a82/mxnet-0.11.0-py2.py3-none-manylinux1_x86_64.whl
> Collecting protobuf>=3.1.0 (from coremltools==0.8->-r scripts/requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/74/ad/ecd865eb1ba1ff7f6bd6bcb731a89d55bc0450ced8d457ed2d167c7b8d5f/protobuf-3.5.2.post1-cp36-cp36m-manylinux1_x86_64.whl
> Collecting MarkupSafe (from Jinja2==2.8->-r scripts/requirements.txt (line 5))
> Collecting pbr>=0.11 (from mock==2.0.0->-r scripts/requirements.txt (line 8))
>   Using cached https://files.pythonhosted.org/packages/e1/ba/f95e3ec83f93919b1437028e989cf3fa5ff4f5cae4a1f62255f71deddb5b/pbr-4.0.2-py2.py3-none-any.whl
> Collecting py>=1.4.33 (from pytest==3.2.5->-r scripts/requirements.txt (line 9))
>   Using cached https://files.pythonhosted.org/packages/67/a5/f77982214dd4c8fd104b066f249adea2c49e25e8703d284382eb5e9ab35a/py-1.5.3-py2.py3-none-any.whl
> Requirement already satisfied: setuptools in ./deps/env/lib/python3.6/site-packages (from pytest==3.2.5->-r scripts/requirements.txt (line 9)) (39.1.0)
> Collecting python-dateutil>=2 (from pandas==0.22.0->-r scripts/requirements.txt (line 10))
>   Using cached https://files.pythonhosted.org/packages/0c/57/19f3a65bcf6d5be570ee8c35a5398496e10a0ddcbc95393b2d17f86aaaf8/python_dateutil-2.7.2-py2.py3-none-any.whl
> Collecting urllib3<1.23,>=1.21.1 (from requests>=2.9.1->-r scripts/requirements.txt (line 14))
>   Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
> Collecting certifi>=2017.4.17 (from requests>=2.9.1->-r scripts/requirements.txt (line 14))
>   Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
> Collecting idna<2.7,>=2.5 (from requests>=2.9.1->-r scripts/requirements.txt (line 14))
>   Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
> Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.9.1->-r scripts/requirements.txt (line 14))
>   Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
> Collecting patsy (from statsmodels==0.8.0->-r scripts/requirements.txt (line 17))
>   Using cached https://files.pythonhosted.org/packages/5d/eb/92c4b45ca47a2dd1339c958636e083b50ffadb5162a599a1cbbe92f89832/patsy-0.5.0-py2.py3-none-any.whl
> Collecting graphviz (from mxnet==0.11->-r scripts/requirements.txt (line 19))
>   Downloading https://files.pythonhosted.org/packages/84/44/21a7fdd50841aaaef224b943f7d10df87e476e181bb926ccf859bcb53d48/graphviz-0.8.3-py2.py3-none-any.whl
> Building wheels for collected packages: scikit-learn
>   Running setup.py bdist_wheel for scikit-learn ... error
>   Complete output from command /opt/turicreate-master/current/deps/env/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8j70qago/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-srk7rrvw --python-tag cp36:
>   Partial import of sklearn during the build process.
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-install-8j70qago/scikit-learn/setup.py", line 247, in <module>
>       setup_package()
>     File "/tmp/pip-install-8j70qago/scikit-learn/setup.py", line 227, in setup_package
>       .format(numpy_req_str, instructions))
>   ImportError: Numerical Python (NumPy) is not installed.
>   scikit-learn requires NumPy >= 1.6.1.
>   Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
>   
>   
>   ----------------------------------------
>   Failed building wheel for scikit-learn
>   Running setup.py clean for scikit-learn
> Failed to build scikit-learn
> Installing collected packages: six, protobuf, numpy, coremltools, scipy, cython, MarkupSafe, Jinja2, argparse, decorator, pbr, mock, py, pytest, python-dateutil, pytz, pandas, pillow, prettytable, urllib3, certifi, idna, chardet, requests, scikit-learn, patsy, statsmodels, wheel, graphviz, mxnet
>   Running setup.py install for scikit-learn ... error
>     Complete output from command /opt/turicreate-master/current/deps/env/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8j70qago/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-y_z09qop/install-record.txt --single-version-externally-managed --compile --install-headers /opt/turicreate-master/current/deps/env/include/site/python3.6/scikit-learn:
>     Partial import of sklearn during the build process.
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-8j70qago/scikit-learn/setup.py", line 247, in <module>
>         setup_package()
>       File "/tmp/pip-install-8j70qago/scikit-learn/setup.py", line 227, in setup_package
>         .format(numpy_req_str, instructions))
>     ImportError: Numerical Python (NumPy) is not installed.
>     scikit-learn requires NumPy >= 1.6.1.
>     Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
>     
>     
>     ----------------------------------------
> Command "/opt/turicreate-master/current/deps/env/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8j70qago/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-y_z09qop/install-record.txt --single-version-externally-managed --compile --install-headers /opt/turicreate-master/current/deps/env/include/site/python3.6/scikit-learn" failed with error code 1 in /tmp/pip-install-8j70qago/scikit-learn/

The system itself has numpy:

> msba01 /opt/turicreate-master/current # emerge -p numpy
> 
> These are the packages that would be merged, in order:
> 
> Calculating dependencies... done!
> [ebuild   R    ] dev-python/numpy-1.10.4 

The source tree has some numpy stuff buried down underneath .../deps//src/boost_1_65_1 and .../deps/env/lib/python3.6/site-packages/ just like the previous version did, so I'm not seeing why there's a problem finding it.

**Comment by znation** [comment] 2018-05-01 21:07
I suspect this is due to the mismatch in Python versions between `./configure` flags and what gets picked up from the system (related to/same root cause as #553).

**Comment by znation** [comment] 2018-06-22 23:17
Should be fixed with the fix for #494.

**Closed** 2018-07-03 00:59 UTC
Labels: 1807, bug, build, p4
