### ISSUE TITLE
oneshot detector segmentation fault or kernel dies

### ISSUE THREAD

**Issue by phelmsgit** [apple/turicreate#2217] opened 2019-08-08 10:29 UTC
Model creation fails if tested on more than a few images. Tried macOS (16 GB RAM), CentOS 9 (28 GB RAM), Ubuntu 18 and 19 (28 GB RAM), but I always get Segmentation fault or kernel killed; tried a combination of python 2.7 and 3.6, same result. I run it against 10-30 images. Sometimes memory usage is high, sometimes not. Tried it with different image sets. Example image set: https://drive.google.com/open?id=1Jq8XD1N48YeBF6OxCYPoi4H3_g2e6v0f
Turicreate is 5.6 (current master).
Code is:
python
import turicreate as tc
starter_images = tc.load_images('./')
starter_images['label'] = starter_images['path'].element_slice(2,-4)
model = tc.one_shot_object_detector.create(starter_images,'label')

**Comment by nickjong** [comment] 2019-08-08 22:09
This seems to be a dupe of #2038. At the very least, we should see if the fix for that issue resolves this one.

**Closed by nickjong** 2019-08-08 22:09 UTC
Labels: bug, duplicate, one shot object detection, toolkits

**Comment by phelmsgit** [comment] 2019-08-09 07:02
When & where is a fix available for this #2038 release so I can test it? Thanks

**Comment by TobyRoseman** [comment] 2019-08-09 18:44
@phelmsgit - #2038 is still open. So there isn't a fix yet. This issue was closed as a duplicate. Please subscribe to #2038 for updates.
