### ISSUE TITLE
User Guide: missing ratings-data.csv

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#480] opened 2018-04-09 23:24 UTC
[Four different pages](https://apple.github.io/turicreate/docs/userguide/?q=ratings-data.csv) in our user guide reference `ratings-data.csv`, but we never tell how to get it.

**Comment by karthikdash** [comment] 2018-05-09 16:35
Hey. Can I work on this?

**Comment by TobyRoseman** [comment] 2018-05-09 19:06
@karthikdash - thanks for offering to help, but this is probably not a good issue to start on. The dataset is not from UCI ML.

We are working on this issue and will hopefully have a solution soon.

**Comment by karthikdash** [comment] 2018-05-11 16:31
Oh, alright. Thanks!

**Comment by afranklin** [comment] 2018-06-19 23:37
Closing as duplicate of https://github.com/apple/turicreate/issues/97

**Closed by afranklin** 2018-06-19 23:37 UTC
Labels: docs
