### ISSUE TITLE
Object detection should give a better error message when it fails on <10.14

### ISSUE THREAD

**Issue by gustavla** [apple/turicreate#632] opened 2018-06-07 02:35 UTC
A macOS version check seems to missing in the detector's `export_coreml` that will make sure it isn't trying to save a NMS model with macOS older than 10.14.

We should error out and offer the following suggestions:
- Upgrade to 10.14
-   Add `include_non_maximum_suppression=False`

We could also automatically fall back to the latter and write a warning, but I don't think I like that option as much.

**Comment by srikris** [comment] 2018-06-07 16:14
@gustavla I agree with the error message and suggestion of the 2 things.

**Comment by znation** [comment] 2018-06-19 23:11
@gustavla @shantanuchhabra This issue doesn't quite make sense to me. Shouldn't we be able to export with NMS, even on 10.12 or 10.13, or Linux, so long as the runtime target is macOS 10.14+ or iOS  12+?

Also, isn't this really the same issue as https://github.com/apple/turicreate/issues/701 ?

**Comment by shantanuchhabra** [comment] 2018-06-25 22:42
Dupe of #701 so closing this.

**Closed by shantanuchhabra** 2018-06-25 22:42 UTC
Labels: 1807, bug, object detection
