### ISSUE TITLE
Image Classifier not utilizing GPU

### ISSUE THREAD

**Issue by mangerlahn** [apple/turicreate#856] opened 2018-07-17 07:57 UTC
I am probably missing something here. Using turicreate 5.0 beta 2, I want to train an Image Classification model. The extraction of image features does run on the GPU (and its fast!), the training itself however doesn't.

I am using the 2017 MacBook Pro with the 2,9GHz i7 and the Radeon Pro 560.

Is the training always on the CPU and everything is working correctly?

Looking through related issues, I have found the following command: 

`tc.toolkits._mxnet_utils.get_mxnet_context()`

For me this returns only the CPU. Could be for CUDA only though, sorry I accidentally mix up some things here..

**Comment by TobyRoseman** [comment] 2018-07-17 17:29
@mangerlahn - This is expected behavior. Only image feature extraction runs on the GPU. The training of the logistic regression model is CPU only.

Also MXNet is only used on Linux, not on macOS. So the command you mention will have no effect since you are using a Mac.

I'm going to close this issue, but let us know if you have any more questions.

**Closed by TobyRoseman** 2018-07-17 17:29 UTC
Labels: question

**Comment by mangerlahn** [comment] 2018-07-17 18:01
Ok, thank you very much!

**Comment by TobyRoseman** [comment] 2018-08-22 17:42
@dustturtle - for information about our image classification toolkit take a look at [that section in our user guide](https://apple.github.io/turicreate/docs/userguide/image_classifier/). Image feature extraction is the 2nd stage mentioned [here](https://apple.github.io/turicreate/docs/userguide/image_classifier/how-it-works.html).

**Comment by JamesDale** [comment] 2018-08-24 13:16
@TobyRoseman @shantanuchhabra are there any plans to support training the logistic regression model via the GPU?

**Comment by TobyRoseman** [comment] 2018-08-24 18:10
@JamesDale - There has been some discussion about this idea, but at the moment we don't have any plans to do it. Feel free to create an issue as a feature request to track this idea.

**Comment by srikris** [comment] 2018-09-08 15:55
I filed an issue to track the use of GPU for the last layer (#1077).
