### ISSUE TITLE
CUDA 9 and cuDNN 7 support

### ISSUE THREAD

**Issue by linthieda** [apple/turicreate#17] opened 2017-12-09 05:02 UTC
Since CUDA 9 and cuDNN 7 has already released, and there are multiple API changes for these low-level libraries. Something like `cudnnGetConvolutionForwardAlgorithm_v7()` may have better performance than older version. We should adapt to these as well.

**Comment by gustavla** [comment] 2017-12-09 05:19
All CUDA code runs through MXNet, which is a deep learning framework. If MXNet supports CUDA 9, then so can we. The problem is that they have not put up a wheel for mxnet-cu90==0.11.0, which is the only version we currently support (there are breaking changes in 0.12).

We hope to extend our MXNet version support soon, in which case we should also get CUDA 9 support for free. I'm not sure what cuDNN they currently support.

**Comment by srikris** [comment] 2017-12-09 22:16
It looks like [mxnet 0.12](https://cwiki.apache.org/confluence/display/MXNET/MXNet+0.12.0+Release+Notes) supports CUDA 7 and 9 so we should try and depend on that version in the next release (of course assuming all our tests pass and the model quality stays the same).

Thanks for the feedback @linthieda!

**Comment by helloniklas** [comment] 2018-01-02 15:12
@gustavla @srikris So I managed to compile from source and run MXNET 1.0.1 on GPU on my MacBook Pro with a Sonnett eGPU and NVIDIA 1080 card.

Since NVIDIA's macOS 10.13.2 driver is only supporting CUDA 9 and not CUDA 8, CUDA 9 is essential for this. I'm also running cuDNN 7 with this setup.

With Turi being an Apple thing and supporting CoreML export for Xcode presumably a lot of users will be on Mac. Would be great if next version will use MXNET 1.0.0 as you will then get GPU support for Mac with NVIDIA cards.

**Comment by gustavla** [comment] 2018-01-03 17:33
@helloniklas We are close to both MXNet 0.12 and 1.0 support. However, the 1.0.0 version causes the object detector to crash (this is fixed in their 1.0.1 nightlies), so we will have to wait until 1.0.1 has been released before we can extend official support to 1.*. Hopefully they release it before our next version so that we can get it in. Thanks for your patience!

**Comment by gustavla** [comment] 2018-01-05 21:45
All changes to support all newer versions of MXNet (which include CUDA 9 from 0.12.1) have been merged in (#129, #169). Unless you do a from source installation, this will all be available in the next release.

**Closed by gustavla** 2018-01-05 21:45 UTC
Labels: enhancement
