### ISSUE TITLE
Turi Create installation on anaconda virtual environment 

### ISSUE THREAD

**Issue by harryjohnlabs** [apple/turicreate#3454] opened 2022-08-11 11:06 UTC
Iam getting is this error i installed python 3.7.0 in virtual environment by using this code 
conda create -n virtual_environment_name2 python=3.7
still its not working
(virtual_environment_name2) C:\Users\MAHE>pip install -U turicreate
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      running bdist_wheel
      running build
      C:\ProgramData\Anaconda3\envs\virtual_environment_name2\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      installing to build\bdist.win-amd64\wheel
      running install

              ==================================================================================
              TURICREATE ERROR

              If you see this message, pip install did not find an available binary package
              for your system.

              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).

              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8

              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`

              ==================================================================================

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
  Running setup.py install for turicreate ... error
  error: subprocess-exited-with-error

  × Running setup.py install for turicreate did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      running install
      C:\ProgramData\Anaconda3\envs\virtual_environment_name2\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,

              ==================================================================================
              TURICREATE ERROR

              If you see this message, pip install did not find an available binary package
              for your system.

              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).

              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8

              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`

              ==================================================================================

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> turicreate

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by TobyRoseman** [comment] 2022-08-11 19:10
TuriCreate does not have native Windows support. If you want to use TuriCreate on Windows, you need to use WSL.

Duplicate of #533.

**Closed as completed by TobyRoseman** 2022-08-11 19:10 UTC
Labels: duplicate
