### ISSUE TITLE
error running `build.sh` on OSX 10.12.6

### ISSUE THREAD

**Issue by evandrix** [apple/turicreate#28] opened 2017-12-09 18:10 UTC
_error message_
```++ python -c 'import turicreate; print(turicreate.version_info.version)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "turicreate/__init__.py", line 30, in <module>
    from turicreate.data_structures.sgraph import Vertex, Edge
  File "turicreate/data_structures/__init__.py", line 18, in <module>
    from . import sframe
  File "turicreate/data_structures/sframe.py", line 16, in <module>
    from ..connect import main as glconnect
  File "turicreate/connect/main.py", line 13, in <module>
    from ..cython.cy_unity import UnityGlobalProxy
ImportError: dlopen(turicreate/cython/cy_unity.so, 2): Symbol not found: _libssh2_agent_connect
  Referenced from: /turicreate/debug/src/unity/python/turicreate/cython/../libunity_shared.dylib
  Expected in: flat namespace
 in /turicreate/debug/src/unity/python/turicreate/cython/../libunity_shared.dylib```

**Comment by srikris** [comment] 2017-12-09 19:21
Are you trying to build turicreate from source? If so, then [you should try out instructions from here](https://github.com/apple/turicreate/blob/master/BUILD.md).

**Comment by falu2010** [comment] 2017-12-14 06:19
I tried to build from source by following instructions mentioned in above link. There is build failure on OSX 10.12.6:

$make -j 4
.......
eferenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found, NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework, NSLocalizedDescription=The bundle “IDEInterfaceBuilderCocoaTouchIntegration” couldn’t be loaded because it is damaged or missing necessary resources.}}}
2017-12-13 22:13:42.982 ibtoold[16590:1351046] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error getting value for parameter key 'class' of extension 'Xcode.InterfaceBuilderKit.PepperIntegration.ConfigurationList' in plug-in 'com.apple.dt.IDE.IDEInterfaceBuilderWatchKitIntegration''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff7f09c2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff93eb248d objc_exception_throw + 48
	2   DVTFoundation                       0x000000010648352d -[DVTExtensionParameter valueForKey:error:] + 0
	3   Foundation                          0x00007fff80a4e78c -[NSArray(NSKeyValueCoding) valueForKey:] + 467
	4   Foundation                          0x00007fff80a4a859 -[NSArray(NSKeyValueCoding) valueForKeyPath:] + 448
	5   Foundation                          0x00007fff80a4a64a -[NSObject(NSKeyValueCoding) valueForKeyPath:] + 260
	6   IDEInterfaceBuilderKit              0x0000000105ad70b6 -[IBPlatform matchesExtension:] + 50
	7   IDEInterfaceBuilderKit              0x0000000105ad726c __42-[IBPlatform extensionsForExtensionPoint:]_block_invoke + 27
	8   IBFoundation                        0x0000000106ac4be9 -[NSSet(IBSetAdditions) ib_setByFilteringUsingBlock:] + 258
	9   IDEInterfaceBuilderKit              0x0000000105ad7223 -[IBPlatform extensionsForExtensionPoint:] + 218
	10  IDEInterfaceBuilderKit              0x0000000105ad632f -[IBPlatform registerMemberConfigurationVariables] + 166
	11  IDEInterfaceBuilderKit              0x0000000105c11e61 -[IBScopedSingletonRegistry init] + 1350
	12  IDEInterfaceBuilderKit              0x0000000105c11901 __43+[IBScopedSingletonRegistry sharedInstance]_block_invoke + 41
	13  libdispatch.dylib                   0x00007fff947628fc _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00007fff947628b9 dispatch_once_f + 38
	15  IDEInterfaceBuilderKit              0x0000000105c118d5 +[IBScopedSingletonRegistry sharedInstance] + 45
	16  IDEInterfaceBuilderKit              0x0000000105a28d05 -[IBInterfaceBuilderPlugin init] + 146
	17  IDEInterfaceBuilderKit              0x0000000105a28c59 +[IBInterfaceBuilderPlugin ide_initializeWithOptions:error:] + 34
	18  IDEFoundation                       0x0000000106dabf42 _IDEInitializeOnePlugInAndPrerequisites + 2324
	19  IDEFoundation                       0x0000000106dab849 _IDEInitializeOnePlugInAndPrerequisites + 539
	20  IDEFoundation                       0x0000000106dab849 _IDEInitializeOnePlugInAndPrerequisites + 539
	21  IDEFoundation                       0x0000000106da9f3e _IDEInitializePlugIns + 1604
	22  IDEFoundation                       0x0000000106da92f5 IDEInitialize + 8547
	23  ibtoold                             0x0000000105720170 ibtoold + 74096
	24  ibtoold                             0x000000010571f2eb ibtoold + 70379
	25  libdyld.dylib                       0x00007fff94798235 start + 1
	26  ???                                 0x000000000000001d 0x0 + 29
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Command /Applications/Xcode.app/Contents/Developer/usr/bin/actool failed with exit code 6

** BUILD FAILED **


The following build commands failed:
	CompileStoryboard Turi\ Create\ Visualization/Base.lproj/Main.storyboard
	CompileAssetCatalog /Users/falgunijhaveri/workspace/turicreate/debug/src/visualization/Debug/Turi\ Create\ Visualization.app/Contents/Resources Turi\ Create\ Visualization/Assets.xcassets
(2 failures)
make[2]: *** [src/visualization/CMakeFiles/visualization_client] Error 65
make[1]: *** [src/visualization/CMakeFiles/visualization_client.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 49%] Linking CXX static library libflexible_type.a
[ 49%] Built target flexible_type
make: *** [all] Error 2

**Comment by znation** [comment] 2018-02-06 20:02
@falu2010 What version of macOS are you running? What version of Xcode do you have installed? We have only tried building latest master on macOS 10.12 and 10.13 with Xcode 9; other versions may or may not work. If you can provide specific versions that don't work, we can try them out.

**Comment by znation** [comment] 2018-03-13 18:04
Closing; unable to reproduce this issue.

**Closed by znation** 2018-03-13 18:04 UTC
Labels: need repro
