### ISSUE TITLE
Drawing classifier must run on Mac GPUs

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#1756] opened 2019-04-20 01:24 UTC
Currently, drawing classifier does not run on the Mac GPUs. We need to:

- [ ] Investigate if this is possible using MacOS 10.14 APIs.
- [ ] Implement after the investigation is complete.

**Comment by shantanuchhabra** [comment] 2019-06-21 23:21
This is a dupe of #1888 , closing this in favor of that.

**Closed by shantanuchhabra** 2019-06-21 23:21 UTC
Labels: drawing classifier, toolkits
