### ISSUE TITLE
Loss is NaN when training object detector on GPU

### ISSUE THREAD

**Issue by jennigato** [apple/turicreate#2465] opened 2019-10-17 12:00 UTC
I know this issue has been submitted before #629, but I'm still experiencing the same issue with Nan losses after the first iteration when training on GPU (works fine on CPU). 

I'm using the latest version of TuriCreate (5.8) on an iMac (late 2013, 3.4 GHz Quad-Core Intel Core i5, 16 GB 1600 MHz DDR3) running macOS Catalina (10.15), with NVIDIA GeForce GTX 775M 2G. Decreasing my batch size to 8 or even lower values didn't help. Is this still being looked at? Thanks.

**Comment by srikris** [comment] 2019-11-18 07:11
@jennigato Any chance you can share a reproducible step for us?

**Comment by rainhut** [comment] 2020-01-02 12:19
Same issue

**Comment by TobyRoseman** [comment] 2020-08-31 21:43
Since we haven't received step to reproduce, I'm going to close this issue. Feel free to reopen with reproduction steps (i.e. code and data).

**Closed by TobyRoseman** 2020-08-31 21:43 UTC
Labels: bug, duplicate, object detection, p2, toolkits, verify
