### ISSUE TITLE
I have arranged my data,but objectDetection data.explore is error.

### ISSUE THREAD

**Issue by HelloWorldYyx** [apple/turicreate#350] opened 2018-03-07 03:04 UTC
```
Materializing SFrame...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-294151549b8b> in <module>()
----> 1 data.explore()

/Users/admin/anaconda2/envs/turi/lib/python2.7/site-packages/turicreate/data_structures/sframe.pyc in explore(self, title)
   4452         if title is None:
   4453             title = ""
-> 4454         self.__proxy__.explore(path_to_client, title)
   4455 
   4456     def show(self):

turicreate/cython/cy_sframe.pyx in turicreate.cython.cy_sframe.UnitySFrameProxy.explore()

turicreate/cython/cy_sframe.pyx in turicreate.cython.cy_sframe.UnitySFrameProxy.explore()

RuntimeError: Exception in python callback function evaluation: 
IndexError('tuple index out of range',): 
Traceback (most recent call last):
  File "turicreate/cython/cy_pylambda_workers.pyx", line 455, in turicreate.cython.cy_pylambda_workers._eval_lambda_by_sframe_rows
  File "turicreate/cython/cy_pylambda_workers.pyx", line 226, in turicreate.cython.cy_pylambda_workers.lambda_evaluator.eval_sframe_rows
  File "/Users/admin/anaconda2/envs/turi/lib/python2.7/site-packages/turicreate/toolkits/object_detector/util/_visualization.py", line 130, in draw_single_image
    _channels=image.shape[2],
IndexError: tuple index out of range
```

**Comment by HelloWorldYyx** [comment] 2018-03-12 01:50
I found that the picture resource contains some pictures. The creation of the model will give an error, but I do not know what the difference between these pictures and the normal picture.

**Comment by abhishekpratapa** [comment] 2018-03-12 08:05
Thanks HelloWorldYyx, thanks for filing the issue! Can you provide me steps to repro this bug so I can better assist you?

**Comment by HelloWorldYyx** [comment] 2018-03-14 08:23
https://www.jianshu.com/p/a67a60a82f61

**Comment by znation** [comment] 2018-07-23 22:12
Hi @HelloWorldYyx, we're unable to reproduce this issue after attempting the steps described in the article you linked, and we have also tried to reproduce unsuccessfully by hypothesizing about the error text and call stack, and testing some other cases as well. Could you please provide a sample of data that will consistently reproduce this issue, and the version of Turi Create you are using? I suspect it's a data-dependent issue. Thanks!

**Comment by znation** [comment] 2018-08-09 20:26
Unable to reproduce. Closing.

**Comment by zoecarver** [comment] 2018-10-14 02:05
I got this issue when trying to set `image_with_ground_truth` before exploring the data.

**Comment by znation** [comment] 2018-10-15 16:31
@zoecarver Could you please provide steps to reproduce this issue? I'm not sure where `image_with_ground_truth` comes from or how to set it in order to reproduce this issue. Thanks!

**Comment by srikris** [comment] 2019-01-17 21:23
Closing this right now. Please re-open if we have a repro.

**Closed by srikris** 2019-01-17 21:23 UTC
Labels: bug, need user repro, p2, visualization
