### ISSUE TITLE
Google Colab : One Shot Object Detection Runtime Crash

### ISSUE THREAD

**Issue by kidboy-man** [apple/turicreate#2917] opened 2020-01-13 09:25 UTC
Hi All!
Recently I tried to implement turicreate one shot object detection(OSOD) to recognize a brand logo. However, since my MacBook doesn't have a GPU, then I tried to run it on google colab notebook.
I managed to have it working until the step of image augmentation, but when I was running the `model = tc.one_shot_object_detector.create(starter_images, 'label', backgrounds=my_backgrounds)
` method, the colab's runtime crashed. What causes this and how to fix this? Has anyone managed to run OSOD in google colab?

**Comment by TobyRoseman** [comment] 2020-01-13 21:46
@kidboy-man - What error message do you get? Can you post the entire output of the call to `tc.one_shot_object_detector.create`?

**Comment by kidboy-man** [comment] 2020-01-14 06:59
@TobyRoseman - There is no error message from kernel, but the colab notebook says that the runtime is crashed. 
![image](https://user-images.githubusercontent.com/56571959/72321240-fa178200-36d5-11ea-8d40-f585e8cd3ad0.png)


You can check my notebook here: https://colab.research.google.com/drive/1hRACSEgMB_ykS7IBxCYh7BI9uq0Q5KfR#scrollTo=ImyHz0wgcfZN

Thank you

**Comment by navanchauhan** [comment] 2020-02-04 04:31
Hi, the link you have posted is dead now

If your issue has been resolved then please close the issue 

Cheers!

**Comment by kidboy-man** [comment] 2020-02-04 11:23
Hi @navanchauhan 
I accidentally deleted the notebook. I already tried to re-run the OSOD but it still crashes the colab runtime. Here, I tried to run the example as written in the documentation. It always crashed at the `model.create` section
https://colab.research.google.com/drive/1iSGetSXK6o24vk64-KrkLwNnna4ojfMv?authuser=1

**Comment by navanchauhan** [comment] 2020-02-04 14:54
Yup, even I am facing the same issue in Google Colab with your notebook, checking the runtime logs it gives a warning about `traitlets` being moved to the top level

Importing that also does not fix the issue and the Kernel keeps restarting

**Comment by TobyRoseman** [comment] 2020-02-04 19:43
@navanchauhan - Could you post the entire runtime logs here please?

I suspect what's happening here is that TuriCreate is running out of memory. I don't know how to check that with Google Colab. . . . . Does anyone know how much memory Google Colab gives you?

**Comment by kidboy-man** [comment] 2020-02-05 02:21
In my runtime, it gives 12GB of RAM and 16GB GPU Memory. 
![image](https://user-images.githubusercontent.com/56571959/73805287-dccb6480-47f8-11ea-988e-ce0bec3b458e.png)

**Comment by kidboy-man** [comment] 2020-02-18 03:47
Hi @TobyRoseman and @navanchauhan , any update on this?

**Comment by navanchauhan** [comment] 2020-02-19 13:01
Nah, I am currently in the middle of my final exams, so I don't have that much time

@TobyRoseman 

```

Timestamp | Level | Message
-- | -- | --
Feb 19, 2020, 6:28:09 PM | WARNING | WARNING:root:kernel 2a721722-82c4-41f5-9f8c-d887b4fddf0f restarted
Feb 19, 2020, 6:28:09 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Feb 19, 2020, 6:24:06 PM | WARNING | warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
Feb 19, 2020, 6:24:06 PM | WARNING | /usr/local/lib/python3.6/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
Feb 19, 2020, 6:22:23 PM | INFO | Adapting to protocol v5.1 for kernel 2a721722-82c4-41f5-9f8c-d887b4fddf0f
Feb 19, 2020, 6:22:21 PM | INFO | Kernel started: 2a721722-82c4-41f5-9f8c-d887b4fddf0f
Feb 19, 2020, 6:11:30 PM | INFO | Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Feb 19, 2020, 6:11:30 PM | INFO | http://172.28.0.2:9000/
Feb 19, 2020, 6:11:30 PM | INFO | The Jupyter Notebook is running at:
Feb 19, 2020, 6:11:30 PM | INFO | 0 active kernels
```

**Comment by shantanuchhabra** [comment] 2020-02-22 18:52
Hi there,

As a first step, let's try to figure out where the problem is coming from. Let's separate out the data augmentation and the model training and see which line crashes before we debug further. Could you try out the following snippet:

```python
import turicreate as tc # Line 0
synthetic_data = tc.one_shot_object_detector.util.preview_synthetic_training_data(training_images, 'label') # Line 1
model = tc.object_detector.create(synthetic_data, batch_size=24, max_iterations=200) # Line 2
```

There are two possible scenarios after running this snippet:
- **Line 1 crashes:** There is something amiss with the synthetic data generated, which is causing a crash. Next steps might involve sifting through the data and making sure all the images look okay and aren't corrupted.
- **Line 2 crashes:** The synthetic data generated is fine. Since both OSOD and OD share the same training code as of now, this would then be an Object Detector issue (independent of the data augmentation that the One Shot Object Detector does), which we can investigate from thereon.

**Comment by navanchauhan** [comment] 2020-02-23 14:14
@shantanuchhabra It crashes at line 1

Is there any chance TC is trying to create a new window displaying the images?

**Comment by tesths** [comment] 2020-02-24 02:09
I think I meet the same issue on turicreate style transfer.

When I use colab for turicreate 6.1 version and train for style transfer.
Colab will crash when I run
`model = tc.style_transfer.create(style, content)`
![WX20200224-100654](https://user-images.githubusercontent.com/8736805/75124943-6b8f1b00-56ed-11ea-8a99-780532d364ee.png)
And I also try for turicreate 5.8 and mxnet, it's run ok.

My colab notebook url is [here](https://colab.research.google.com/drive/119DLUOvtmF7JCDitrdQJOv5F8GmweIKN).

**Comment by TobyRoseman** [comment] 2020-02-24 23:57
@tesths - I do not think this issue is the same problem you are experiencing. I suggest you create a new issue.

@navanchauhan - I really don't think [any part of that code](https://github.com/apple/turicreate/blob/58a93d45718a560bb93c944673ecd2cc797423a2/src/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py#L65) should be trying to create a new window.

**Comment by navanchauhan** [comment] 2020-03-03 17:14
Could someone try running OSOD using Jupyter-Labs on their systems? My Jupyter installation has gone bonkers and I am not able to test it out

**Comment by ebolotin6** [comment] 2020-04-20 17:24
Facing the same issue. Kernel keeps crashing as training commences. Log: warn("IPython.utils.traitlets has moved to a top-level traitlets package.")

**Comment by ebolotin6** [comment] 2020-04-21 02:34
> Facing the same issue. Kernel keeps crashing as training commences. Log: warn("IPython.utils.traitlets has moved to a top-level traitlets package.")

I discovered the reason for this. Certain (pytorch) tensors in my code were not sent to CUDA (on accident). The problem is that Colab didn't return the appropriate Pytorch traceback message for this error but instead crashed.

To discover what the problem actually was, I ran my code on jupyterlab on Floydhub. During testing jupyter returned the appropriate traceback message - which I then fixed and was able to run the code successfully (both on Floydhub and Colab).

**Comment by navanchauhan** [comment] 2020-05-22 05:38
@kidboy-man can you try from a fresh notebook? https://colab.research.google.com/drive/14bFRa4ygtd1PDcBn4Zb8BH23MUEWMg2L?usp=sharing OSOD is no longer crashing

**Comment by TobyRoseman** [comment] 2020-08-31 19:26
Is this still an issue with the latest version of TuriCreate?

**Comment by TobyRoseman** [comment] 2020-10-03 00:13
Closing due to inactivity. Please reopen if this is still and issue in the latest version of TuriCreate.

**Closed by TobyRoseman** 2020-10-03 00:13 UTC
Labels: need turi repro, one shot object detection
