### ISSUE TITLE
Question: How to access/use  just want the SFrame

### ISSUE THREAD

**Issue by javadba** [apple/turicreate#1428] opened 2019-02-18 20:13 UTC
I am only interested in alternatives to the pandas dataframe. Where/how can we access the (updated/improved?) SFrame *only* - and not the extra "make ML easy" mechanisms around it?

**Comment by srikris** [comment] 2019-02-18 21:59
Making an SFrame as a separate package is a great feature request. Thanks for posting it here.

**Comment by znation** [comment] 2019-02-20 06:51
Duplicate of #1273. Please follow that thread for more info, thanks!

**Closed by znation** 2019-02-20 06:51 UTC
Labels: build
