### ISSUE TITLE
Support short sessions in Activity Classifier

### ISSUE THREAD

**Issue by vmalyi** [apple/turicreate#813] opened 2018-07-03 19:59 UTC
Hi everyone,

after reading the [introduction to Activity Classifier ](https://apple.github.io/turicreate/docs/userguide/activity_classifier/) I can't understand the reason for using sessions both in data for activity classifier and during the process of creating/training of Activity Classifier.

The following official explanation is clear to me:
_Each set of consecutive samples produced from a single recording of a subject is called a session. A session can contain demonstrations of multiple activities. However, sessions aren't required to contain all activities or be of the same length. The input data to the activity classifier must contain a column to uniquely assign each sample to a session..._

However, I don't understand the reason why Activity Classifier need to strictly associate samples with specific sessions?

PS: this question arose after trying to use Activity Classifier for my multi-class human activity recognition problem. Unfortunately, the performance of Activity Classifier available in Turi Create was way lower than the one I already utilize in my project and I'm trying to identify potential issues which could affect the accuracy of Turi's Activity Classifier like the usage of sessions which I mentioned above.

Thanks!

**Comment by igiloh** [comment] 2018-07-04 09:08
Hi @vmalyi, 

Thank you for trying out the Activity Classifier, and for the elaborate feedback!

As you can imagine - the session id is indeed stripped in the pre-processing stage. Before training the NN - the sessions are being cropped into non-overlapping, constant length time sequences.  These constant length sequences (let's denote them "chunks") are the actual training samples being fed to the network.

The main motivation behind the session id requirement is to make sure that samples from two separate users don't get into the same chunk (instead - the last chunk of each sessions is being padded and then weighted out by the loss function).  
Another advantage of using sessions is it provides a single identification for consecutive data from a specific user. If we would have used time stamps only - data from two different users taken at the same time might have gotten intermixed. Or alternatively by using user_id only - two different recordings, taken at completely different times might have been fused together in the same chunk.  
Lastly - using sessions improves the train-test split mechanism. Splitting whole sessions increases the test set's independence, by making sure that correlated chunks coming from the same user don't end up in both the training and the test set. 

Can you please share some more information about your human activity recognition problem, and the algorithms you've been comparing with?  
The AC have been tested with several similar datasets (multi-class human activities, such as running, walking etc.). We have tried to design the AC to generalize well for a wide variety of datasets.  
Any additional information would be of course welcome - as we try to improve AC performance even further.

**Comment by vmalyi** [comment] 2018-07-04 11:00
hi @igiloh and thanks for such a broad answer!

Now the logic behind using session IDs is clear to me.

I work on http://autoworkout.app/ which currently recognizes 11 activities using 3 deep feedforward NN s each fed with accelerometer data from X, Y, Z axis respectively and each having accuracy of ~0.91% +- 0.05% and F1-score of 0.92 +- 0.01. All 3 NNs work in an ensemble and there is a custom algorithm which makes a final prediction. Predictions are made each ~1.8 seconds.

And even with the accuracy stated above I still feel a need for improving it, because it's critical from the user's perspective. I gave Turi Create a quick try and was able to reach only 45-51% accuracy (trained on 1120 sessions) even after extensively searching for optimal hyperparameters. The data Turi's activity classifier was trained on was the same, AutoWorkout's one had been trained on.

And here is a small excerpt of training data from a single recording session, containing a single activity:

![training_data](https://user-images.githubusercontent.com/1609148/42273346-328498ea-7f89-11e8-836c-8339ca49ca3e.png)

While looking for the ways of improving Turi's classifier performance, I thought that probably the data format could be an issue in my case: the whole dataset consists of recording sessions 10 seconds long, containing a single actor and a single activity each. But according to your explanation such a format is rather expected from Turi, so there should not be an issue.

Another proble, which is coming to my mind is the absence of gyroscope samples in training data (in case of AutoWorkout classifier, gyroscope data didn't contribute a lot into the accuracy).

Is there anything else I should take a look to to improve Turi's classifier performance?

Thanks!

**Comment by igiloh** [comment] 2018-07-04 12:39
Hi @vmalyi ,

Thanks for the elaborate reply! 

It is indeed peculiar that you see such a big difference in performance (91% vs 45%). Sounds like something is off. I would indeed suspect some incorrect usage of the AC.  
I do have a few ideas right off the bat (will elaborate later) - but it would be best to just try to investigate with the actual data.

Would it be possible for you to share a subset of your data with us in a secure manner? And also the code you have used to train it with the AC?

Thanks!

**Comment by vmalyi** [comment] 2018-07-04 19:03
@igiloh, I invited you as a collaborator to the [repo](https://github.com/vmalyi/turi_create_classifier_experiment) containing the *.sframe I used to train classifier on and jupyter notebook containing the classifier itself.

Let me know your thoughts on what could possible go wrong with my approach.

**Comment by igiloh** [comment] 2018-07-05 08:52
Thank you very much!

We will analyze the dataset and get back to you soon.

**Comment by vmalyi** [comment] 2018-07-16 12:55
hey @igiloh, 

did you have a chance to look into this?

**Comment by igiloh** [comment] 2018-07-16 14:29
Hi @vmalyi - Yeah, I'm just summarizing my experiments and pushing an updated notebook to your repo.  
May I publish it here as well, for future reference?

**Comment by igiloh** [comment] 2018-07-16 14:56
@vmalyi - would you mind sharing with me the timestamps column for the data in your SFrame?  

From the screenshot you've attached - it seems that the intended sampling rate was 20Hz (i.e. 0.05 sec between samples).  
However - there seem to be a big variation in the sampling rate. Some of the samples seem to be 0.01s apart, while others are 0.08sec.  
I'm not sure whether this is a real problem. However - as the AC was designed for sensor readings at a constant rate - I wonder if that affects the performance as well. I would like to try and interpolate the data at a constant rate of 20Hz - and see if the performance is a bit better.

**Comment by igiloh** [comment] 2018-07-16 21:47
Hi @vmalyi,

Please see attached a [notebook](https://github.com/apple/turicreate/files/2199413/auto_workout_classifier_turi-create.ipynb.zip) with my analyses.  

I'm afraid that my main conclusion is that I couldn't find any set-up in which the AC performs significantly better on this dataset.  
The main reason, I believe, are the short sessions. Having short sessions of 10 sec each, with a prediction window of 2 seconds - means that every session only has about 5 windows on it.  
Since the RNN in the AC is learning across these windows - having such short sequences (5 samples long) makes it hard for the RNN to gain much knowledge.

I'm leaving this issue open, and changing it to a feature request.  
We would definitely take this use case in consideration, in future development of the Activity Classifier. There is no reason why datasets like yours shouldn't be supported.

**Comment by znation** [comment] 2018-07-17 00:12
@igiloh Can you please re-title this issue to reflect the feature being requested? Thanks!

**Comment by vmalyi** [comment] 2018-07-17 09:11
@igiloh, thanks for your analysis!

@znation I've renamed the issues to sound more appropriate.

**Comment by znation** [comment] 2018-07-17 21:47
Thanks @vmalyi!

**Comment by tetreault** [comment] 2018-08-11 22:29
Total machine learning noob here but came across Turi because I have a task that requires somewhat reliably going from standing-to-kneeling posture (and ideally vice versa). I was following along with the documentation, and made sure my preprocessed CSV mirrors the format used in the table in the "advanced usage" section. 

I'm running the following python script to generate a model: 

```
import turicreate as tc
dataSFrame = tc.SFrame('motion_data_all.csv')

# Train/test split by recording sessions
train, test = tc.activity_classifier.util.random_split_by_session(dataSFrame, session_id='exp_id', fraction=0.8)

# Create an activity classifier
motion_model = tc.activity_classifier.create(train, session_id='exp_id', target='motion', prediction_window=50)

metrics = motion_model.evaluate(test)
print(metrics['accuracy'])

# Save the model for later use in Turi Create
motion_model.save('motion_model.model')

# Export for use in Core ML
motion_model.export_coreml('MotionActivityClassifier.mlmodel')

# try out the model 
model_test_data = dataSFrame[(dataSFrame['motion'] == 'sit') & (dataSFrame['exp_id'] == 1)][500:1000]
motion_model.predict(model_test_data, output_frequency='per_window')
```

My training data is extremely small, as far as ML training data goes. Approx 3.5k rows of standing/sitting/kneeling, each accurately labeled. In the doc you use the HAPT data and then process it into a format with `exp_id` and the activity label. My data set mirrors that end result. 

When I run the following line in spyder: 

```
metrics = motion_model.evaluate(test)
print(metrics['accuracy'])
```

I get the following error: `ToolkitError: Size of prediction probability vector(3) != number of classes(1).`

Just to be clear I'm not completely messing up from the start, I've included some screenshots from the file I use with the following: `dataSFrame = tc.SFrame('motion_data_all.csv')`.

<img width="755" alt="screenshot 2018-08-11 18 24 19" src="https://user-images.githubusercontent.com/5934354/43996590-278bee60-9d94-11e8-8e00-3c38a1cb9838.png">
<img width="764" alt="screenshot 2018-08-11 18 24 34" src="https://user-images.githubusercontent.com/5934354/43996592-2de67262-9d94-11e8-9188-acac9ca507fa.png">

When I run the line: `motion_model = tc.activity_classifier.create(train, session_id='exp_id', target='motion', prediction_window=50)` I get the following output: 
<img width="606" alt="screenshot 2018-08-11 18 28 13" src="https://user-images.githubusercontent.com/5934354/43996600-6aac9082-9d94-11e8-83f3-2ea9ce9f13e6.png">

Every project is unique so I don't expect anyone to debug this for me but any advice pointing me on what to read to learn how to resolve/understand that following error (`ToolkitError: Size of prediction probability vector(3) != number of classes(1).`) would be great.

**Comment by vmalyi** [comment] 2018-08-12 16:13
hey @tetreault, want to probably move your post to a separate thread?

**Comment by igiloh** [comment] 2018-08-12 18:56
Thanks @vmalyi, I was just about to suggest the same.  
@tetreault You seem to be experiencing  a different problem than the one @vmalyi have reported. I would suggest starting your own thread so we can better track this issue.

**Comment by igiloh** [comment] 2018-08-12 19:28
@tetreault - in the meantime, here are some steps we can try to debug the error you are receiving (I'll move this post to the new thread when available):

First - please verify that you use the latest `turicreate` version, 5.0b3. There was a bug recently fixed in `random_split_by_session()`. You can do it by either running `pip freeze | grep turicreate` in shell, or `print tc.__version__` in python.

In addition, can you please provide the output of the following prints?
```
len(dataSFrame['exp_id'].unique())
len(train['motion].unique())
len(test['motion].unique())
```
It seems that your train set only contains two sessions? Is that correct?  
The train set should contain examples from all supported activities. During training a mapping is created that maps all supported activities to integers, and this mapping is used by the prediction/evaluation functions. It is also advisable that the test set contain a mixture of all activities (though not mandatory).

I'm surprised you even got a valid train-test split. The `random_split_by_session()` function is not intended for very small datasets - from the very reason that it is not likely to randomly include all activities if the data is too small. It should have errored out and refuse to do the split below a certain number of sessions (currently hard coded to 100).

**Comment by tetreault** [comment] 2018-08-12 20:12
Hey guys! Sorry for hijacking this thread my mistake :) I understand if this should be in a new thread. 

For starters, I'm definitely using an older version, in my console I see `turicreate==4.3.2` which is just what pip installed. 

Overall my data i'm loading in to the SFrame has 4 sessions. 

The lines you asked me to run above result in the following: 

```
len(dataSFrame['exp_id'].unique()) # outputs 4
len(train['motion'].unique()) # outputs 3
len(test['motion'].unique()) # outputs 1
```

So therein lies the problem I suppose, if I get the error `ToolkitError: Size of prediction probability vector(3) != number of classes(1).` and i'm seeing 3 of the sessions are in train, but only 1 in test?

Thanks again for your time and response, as I mentioned I'm treading in very new water and am unfamiliar with ML as a whole but slowly trying to work on it!

**Comment by tetreault** [comment] 2018-08-12 20:15
made a new thread here: https://github.com/apple/turicreate/issues/964

**Comment by srikris** [comment] 2019-04-18 03:06
@vmalyi We are trying to investigate this issue. It looks like the repo you have been working on is closed. Is there any chance we can get access again to this?

**Comment by srikris** [comment] 2019-04-20 01:17
@vmalyi After reproducing the issue, we have verified that a simple augmentation fix (using a rolling window instead of a tumbling window) significantly increases the performance. Until this makes into the next release, you can use this code to work around and improve the accuracy.


```python
sessions = train['session_id'].unique()

# Now create a simple rolling window augmentation
train_augmented = train[train['session_id'] == sessions[0]]

for s in sessions[1:]:
    session_data = train[train['session_id'] == s]
    for i in range(1, prediction_window, overlapping_window_size):
        augmented_session = session_data[I:]
        augmented_session['session_id'] = augmented_session['session_id'] + 100000 * i
        train_augmented = train_augmented(augmented_session)
```

Now you can train on the augmented data and the accuracy is 30% better than the original data on this particular dataset.

**Comment by shreyajain17** [comment] 2019-05-15 23:59
On further investigation, we have found that the dataset provided was sorted by labels and hence, the sessions were split up across the multiple labels. While the activity classifier in Turi Create expects the samples associated with each session id to be in an ascending order by time. Do you by any chance have data which has the session id preserved in order?

**Comment by shreyajain17** [comment] 2019-05-21 16:40
Closing the issue for now since we do not have data in the right format.

**Closed by shreyajain17** 2019-05-21 16:40 UTC
Labels: activity classifier, feature request, p1, toolkits
