### ISSUE TITLE
build_cpp_linux_no_remotefs

### ISSUE THREAD

**Issue by abhishekpratapa** [apple/turicreate#2594] opened 2019-11-11 19:37 UTC
This build fails with:

```
usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
src/model_server/CMakeFiles/unity_shared.dir/build.make:1111: recipe for target 'src/model_server/libunity_shared.so' failed
make[2]: *** [src/model_server/libunity_shared.so] Error 1
CMakeFiles/Makefile2:967: recipe for target 'src/model_server/CMakeFiles/unity_shared.dir/all' failed
make[1]: *** [src/model_server/CMakeFiles/unity_shared.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by syoutsey** [comment] 2019-11-19 21:12
@abhishekpratapa can you verify if this is fixed, and if so close the issue?

**Comment by znation** [comment] 2019-11-19 23:46
It's not fixed. Still happens to me.

**Comment by znation** [comment] 2019-11-20 10:00
Dupe of #2302

**Closed by znation** 2019-11-20 10:00 UTC
Labels: bug, build, p1
