### ISSUE TITLE
training_iterations in .mlmodel is always 1 when using GPU on macOS 10.14

### ISSUE THREAD

**Issue by unclenorton** [apple/turicreate#677] opened 2018-06-15 14:51 UTC
Here's my scenario:

1. Using dataset from here: https://lear.inrialpes.fr/people/marszalek/data/ig02/
1. Following this: https://apple.github.io/turicreate/docs/userguide/object_detection/data-preparation.html for data preparation/generating SFrame
1. Following this: https://apple.github.io/turicreate/docs/userguide/object_detection/ to train the model

Training with turicreate 5.0b1 on a Late 2013 Macbook Pro with GT 750M. As expected, it is using GPU by default, doing 5000 iterations, and everything looks fine in the output, except that when used in a CoreML app, the model doesn't recognise anything.

Opening the .mlmodel file in an editor reveals that there's a line having `training_iterations1�`. At the same time, the .mlmodel file from [this example](https://developer.apple.com/documentation/vision/recognizing_objects_in_live_capture), has it as `training_iterations4000�` there, which made me suspect there's something wrong. I have then tried to re-run the training with `max_iterations` set to 15, but the output still had 1 (although `max_iterations` was 15 inside .mlmodel, as expected).

However, using `tc.config.set_num_gpus(0)` to force CPU-only computation yielded the correct result: both `training_iterations` and `max_iterations` was 15.

So it looks like a GPU rendering issue, but I am not sure if I there's any way to actually detect when and why it happens. On a side note, I am also experiencing [Issue #88](https://github.com/apple/turicreate/issues/88)

**Comment by gustavla** [comment] 2018-06-19 00:07
I can confirm this bug. It happens when IO threads are enabled (that code path just does not update `iterations`). @unclenorton Thanks for taking the time to report this. We appreciate it!

It looks like this will be fixed when #674 is merged.

**Comment by znation** [comment] 2018-07-20 20:43
Fixed with #674.

**Closed by znation** 2018-07-20 20:43 UTC
