### ISSUE TITLE
Activity Classification Code Needs Updating for Python 3

### ISSUE THREAD

**Issue by Digital-Rabbit** [apple/turicreate#1159] opened 2018-10-24 23:08 UTC
In
https://apple.github.io/turicreate/docs/userguide/activity_classifier/data-preparation.html
data = data.filter_by(target_map.keys(), 'activity_id')
Need to be updated to:
data = data.filter_by(list(target_map.keys()), 'activity_id')
Since in Python 3, dict.keys() no longer returns a list.

**Comment by nickjong** [comment] 2018-10-26 20:12
Close as a dupe of #1140

**Closed by nickjong** 2018-10-26 20:12 UTC
Labels: python3
