### ISSUE TITLE
Text classifier predictions on Xcode

### ISSUE THREAD

**Issue by emannuelOC** [apple/turicreate#174] opened 2018-01-11 18:27 UTC
After importing the model created with the sentence_classifier into Xcode, I got the following error:

`Error Domain=com.apple.CoreML Code=1 "Predicted feature named 'rating' was not output by pipeline"`

`rating` was the name of the target variable in my dataset.

Here's the code I used to create the model:

`import turicreate as tc`
`data = tc.SFrame('sentiment-train.tsv')`
`model = tc.sentence_classifier.create(data, 'rating', features=['text'])`
`model.export_coreml('MyModel.mlmodel')`

p.s. I couldn't build `turicreate` locally on my machine so I've updated the code in the `_sentence_classifier.py` according to the one in #58. I know that's not the ideal and it may be causing the problem but it was the only way I could try exporting the model.

**Comment by srikris** [comment] 2018-01-16 17:24
I'd recommend building on your machine so its easier for us to triage and identify the issue. Otherwise, it could be a symptom of your system. 

What trouble did you have building? Were you able to follow the instructions on BUILD.md to make that happen?

**Comment by emannuelOC** [comment] 2018-01-18 15:14
I got the following erros when running `make -j 8`:

`
Command /bin/sh failed with exit code 127

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/emannuelcarvalho/Developer/turicreate/debug/src/visualization/Turi\ Create\ Visualization.build/Debug/Turi\ Create\ Visualization.build/Script-FC1A878A1FB14D2900A67DAD.sh
(1 failure)
make[2]: *** [src/visualization/CMakeFiles/visualization_client] Error 65
make[1]: *** [src/visualization/CMakeFiles/visualization_client.dir/all] Error 2
`

**Comment by emannuelOC** [comment] 2018-01-18 17:14
Now I'm getting an error when I try to import `turicreate`:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-5e19a42750e5> in <module>()
----> 1 import turicreate as tc

/Users/emannuelcarvalho/Developer/turicreate/debug/src/unity/python/turicreate/__init__.py in <module>()
     28 from turicreate.version_info import __version__
     29 
---> 30 from turicreate.data_structures.sgraph import Vertex, Edge
     31 from turicreate.data_structures.sgraph import SGraph
     32 from turicreate.data_structures.sarray import SArray

/Users/emannuelcarvalho/Developer/turicreate/debug/src/unity/python/turicreate/data_structures/__init__.py in <module>()
     15 __all__ = ['sframe', 'sarray', 'sgraph', 'sketch', 'image']
     16 
---> 17 from . import image
     18 from . import sframe
     19 from . import sarray

ImportError: cannot import name image
```

**Comment by emannuelOC** [comment] 2018-01-19 00:14
After building, I was able to export the model to the .mlmodel format and use it in Xcode but the problem persists.

Here's the code I used to create and export the model:

```
>>> import turicreate as tc
>>> data = tc.SFrame('sent_train.csv')
Finished parsing file /Users/emannuelcarvalho/Developer/sent_train.csv
Parsing completed. Parsed 100 lines in 0.053013 secs.
------------------------------------------------------
Inferred types from first 100 line(s) of file as 
column_type_hints=[int,str]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------
Finished parsing file /Users/emannuelcarvalho/Developer/sent_train.csv
Parsing completed. Parsed 7086 lines in 0.021544 secs.
>>> model = tc.sentence_classifier.create(data, 'sentiment', features=['text'])
PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.

Logistic regression:
--------------------------------------------------------
Number of examples          : 6745
Number of classes           : 2
Number of feature columns   : 1
Number of unpacked features : 2952
Number of coefficients    : 2953
Starting L-BFGS
--------------------------------------------------------
+-----------+----------+-----------+--------------+-------------------+---------------------+
| Iteration | Passes   | Step size | Elapsed Time | Training-accuracy | Validation-accuracy |
+-----------+----------+-----------+--------------+-------------------+---------------------+
| 1         | 3        | 0.000148  | 1.281354     | 0.987250          | 0.950147            |
| 2         | 5        | 1.000000  | 1.536147     | 0.996145          | 0.961877            |
| 3         | 6        | 1.000000  | 1.681825     | 0.997924          | 0.961877            |
| 4         | 7        | 1.000000  | 1.856880     | 0.999259          | 0.976540            |
| 5         | 8        | 1.000000  | 2.030388     | 0.999703          | 0.976540            |
| 6         | 9        | 1.000000  | 2.191586     | 0.999852          | 0.976540            |
| 10        | 13       | 1.000000  | 2.872957     | 1.000000          | 0.976540            |
+-----------+----------+-----------+--------------+-------------------+---------------------+
TERMINATED: Iteration limit reached.
This model may not be optimal. To improve it, consider increasing `max_iterations`.
>>> model.export_coreml('ClassifierModel.mlmodel')
Saving valid model to path ClassifierModel.mlmodel
```

And here's the swift code:

```
let bagOfWords = bow(text: "I think that was awesome!")
        do {
            let prediction = try ClassifierModel().prediction(text: bagOfWords)
            print(prediction)
        } catch {
            print(error)
        }
```

It output the error bellow:
```
Error Domain=com.apple.CoreML Code=1 "Predicted feature named 'sentiment' was not output by pipeline" UserInfo={NSLocalizedDescription=Predicted feature named 'sentiment' was not output by pipeline}
```

Maybe there's a problem with my dataset?

I uploaded the csv file [here](https://github.com/emannuelOC/emannuelOC.github.io/tree/master/turicreate) in case you wanna reproduce exactly the same situation.

**Comment by znation** [comment] 2018-01-19 04:29
Thanks @emannuelOC - I'll investigate from here.

**Comment by srikris** [comment] 2018-01-21 18:29
@emannuelOC Thanks for catching this issue. The issue is related to #98 and we will continue to investigate. It seems that this happens when you have a new word during prediction time. We have narrowed down this issue and hope to get a fix out soon.

**Comment by znation** [comment] 2018-01-24 00:11
Dupe of #98 (it's the same issue). @srikris, please verify both when closing #98.

**Closed by znation** 2018-01-24 00:11 UTC
