### ISSUE TITLE
Turi Create is not using the appropriate logging level

### ISSUE THREAD

**Issue by iMerica** [apple/turicreate#1643] opened 2019-03-20 21:31 UTC
Hi again,

This is related to #1197. Basically Turi Create is not obeying Python conventions around logging.

Heres an example:

```
worker_1    | [2019-03-20 21:25:40,470: WARNING/ForkPoolWorker-1] Logistic regression:
worker_1    | [2019-03-20 21:25:40,470: WARNING/ForkPoolWorker-1] --------------------------------------------------------
worker_1    | [2019-03-20 21:25:40,470: WARNING/ForkPoolWorker-1] Number of examples          : 11
worker_1    | [2019-03-20 21:25:40,471: WARNING/ForkPoolWorker-1] Number of classes           : 2
worker_1    | [2019-03-20 21:25:40,471: WARNING/ForkPoolWorker-1] Number of feature columns   : 1
worker_1    | [2019-03-20 21:25:40,471: WARNING/ForkPoolWorker-1] Number of unpacked features : 12
worker_1    | [2019-03-20 21:25:40,471: WARNING/ForkPoolWorker-1] Number of coefficients      : 13
worker_1    | [2019-03-20 21:25:40,471: WARNING/ForkPoolWorker-1] Starting Newton Method
worker_1    | [2019-03-20 21:25:40,472: WARNING/ForkPoolWorker-1] --------------------------------------------------------
worker_1    | [2019-03-20 21:25:41,471: WARNING/ForkPoolWorker-1] +-----------+----------+--------------+-------------------+
worker_1    | [2019-03-20 21:25:41,471: WARNING/ForkPoolWorker-1] | Iteration | Passes   | Elapsed Time | Training Accuracy |
worker_1    | [2019-03-20 21:25:41,471: WARNING/ForkPoolWorker-1] +-----------+----------+--------------+-------------------+
worker_1    | [2019-03-20 21:25:41,472: WARNING/ForkPoolWorker-1] | 0         | 1        | 1.000659     | 0.090909          |
worker_1    | [2019-03-20 21:25:41,472: WARNING/ForkPoolWorker-1] | 1         | 2        | 1.001875     | 1.000000          |
worker_1    | [2019-03-20 21:25:41,473: WARNING/ForkPoolWorker-1] | 2         | 3        | 1.002653     | 1.000000          |
worker_1    | [2019-03-20 21:25:41,474: WARNING/ForkPoolWorker-1] | 3         | 4        | 1.003442     | 1.000000          |
worker_1    | [2019-03-20 21:25:41,475: WARNING/ForkPoolWorker-1] | 4         | 5        | 1.004323     | 1.000000          |
worker_1    | [2019-03-20 21:25:41,475: WARNING/ForkPoolWorker-1] | 5         | 6        | 1.005011     | 1.000000          |
worker_1    | [2019-03-20 21:25:41,476: WARNING/ForkPoolWorker-1] | 6         | 7        | 1.005779     | 1.000000          |
worker_1    | [2019-03-20 21:25:41,476: WARNING/ForkPoolWorker-1] +-----------+----------+--------------+-------------------+
worker_1    | [2019-03-20 21:25:41,477: WARNING/ForkPoolWorker-1] SUCCESS: Optimal solution found.
```

This the output of a Turi script running in Celery with `--loglevel=WARNING`. The content of the printed output is NOT a warning at all. It's informational debug content, yet it uses WARNING nonetheless.

Please review the Python docs on logging levels and update Turi to use appropriate logging levels.

Thank you,

Michael

**Comment by TobyRoseman** [comment] 2019-03-20 22:26
This has the same root cause as #145. So I'm going to close this issue as a duplicate. I agree this is broken and we should fix it.

@iMerica - at least in the example you give, you could suppress this output by passing `verbose=True` to `turicreate.logistic_classifier.create(...)`. Many other Turi Create operations also have a `verbose` parameter which is set to `True` by default.

**Closed by TobyRoseman** 2019-03-20 22:26 UTC
