### ISSUE TITLE
Following the OSOD Userguide leads to empty predictions

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#2964] opened 2020-01-28 18:01 UTC
Spawning a thread off of #2954, since TC 6.0, following the OSOD userguide example leads to the following predictions, one of which is empty:

```
In [5]: test_images['predictions']
Out[5]: 
dtype: list
Rows: 2
[[{'confidence': 0.839602530002594, 'type': 'rectangle', 'coordinates': {'y': 1084.5119646191597, 'x': 1337.392183020711, 'height': 110.98627471923828, 'width': 92.3020248413086}, 'label': 'stop_sign'}, {'confidence': 0.6565481424331665, 'type': 'rectangle', 'coordinates': {'y': 941.4400759339333, 'x': 821.407379642129, 'height': 162.8949432373047, 'width': 137.65138244628906}, 'label': 'stop_sign'}], []]
```

**Comment by fareeha** [comment] 2020-02-07 21:27
**Update**: No repro for the issue yet. I've asked user for Platform used, GPU and TC version on the original issue.

Using the userguide demo, found no empty predictions on Mac & Linux on TC==6.0 (from PyPI) and `master` with the default 5k iterations. Lower number of iterations did show empty predictions (tried 100 iterations).

Found performance difference between Mac and Linux on demo example and opened an issue https://github.com/apple/turicreate/issues/2995

**Comment by TobyRoseman** [comment] 2020-09-15 19:27
I also can not reproduce this issue (using Turicreate 6.4); following the instructions in the User Guide, both of the test set images get predictions.

Since the creator of #2954 never got back to us regarding their setup, I'm going to close this issue.

**Closed by TobyRoseman** 2020-09-15 19:27 UTC
Labels: docs, one shot object detection, toolkits
