### ISSUE TITLE
Trying to install

### ISSUE THREAD

**Issue by MatthewGCampbell** [apple/turicreate#2161] opened 2019-07-24 01:18 UTC
Which way would you recommend installing turicreate preferably the easiest way. Tried using Jupiter Notebook like in the WWDC 2018 video, but I was having trouble importing turicreate into the environment. It always said that my python is too new and that I need v.3.6 bu ti have 3.7. does anyone know how to downgrade python using anaconda?

**Comment by MatthewGCampbell** [comment] 2019-07-24 01:52
<img width="1114" alt="Screen Shot 2019-07-23 at 9 51 57 PM" src="https://user-images.githubusercontent.com/31420840/61758769-1b855a00-ad94-11e9-91a9-8674dda535df.png">
now I'm getting this issue

**Comment by TobyRoseman** [comment] 2019-07-24 16:25
Turi Create doesn't yet support Python 3.7. That issue is being tracked in #788.

Based on the paths in your stack trace, it looks like you've figured out how to create a Python 3.6 environment using anaconda.

I'm not sure what's happening with your second issue. Please share the entire stack trace. From just the part you've shared I can't tell what is happening.

**Comment by MatthewGCampbell** [comment] 2019-07-24 17:21
<img width="1327" alt="Screen Shot 2019-07-23 at 1 54 11 PM" src="https://user-images.githubusercontent.com/31420840/61814343-e28dc980-ae15-11e9-8cb7-77281a996018.png">
<img width="1321" alt="Screen Shot 2019-07-23 at 1 54 21 PM" src="https://user-images.githubusercontent.com/31420840/61814344-e28dc980-ae15-11e9-9749-e8b51ca392ed.png">
these might help if their the right screenshots

**Comment by MatthewGCampbell** [comment] 2019-07-24 17:21
I resolved my issue thanks tho

**Comment by MatthewGCampbell** [comment] 2019-07-24 18:35
**now I've got this problem** 
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0025.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":516		y:337	width:466	height:477}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0025.png
	1: [{"label": ... ht":477}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0023.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":556		y:378	width:638	height:620}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0023.png
	1: [{"label": ... ht":620}}]
13 lines failed to parse correctly
Finished parsing file /Users/matthew/annotations/annotations.csv
Parsing completed. Parsed 0 lines in 0.029099 secs.
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0015.png,"[{""label"":""cookie"",type:""rectangle"",coordinates:{""x"":1938	y:1302	width:3434	height:2393}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0015.png
	1: [{"label": ... ht:2393}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0018.png,"[{""label"":""croissant"",type:""rectangle"",coordinates:{""x"":312	y:233	width:539	height:427}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0018.png
	1: [{"label": ... ght:427}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0017.png,"[{""label"":""croiss"",type:""rectangle"",coordinates:{""x"":370	y:640	width:631	height:368}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0017.png
	1: [{"label": ... ght:368}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0020.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":528		y:495	width:1009	height:920}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0020.png
	1: [{"label": ... ght:920}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0019.png,"[{""label"":""croissant"",type:""rectangle"",coordinates:{""x"":330	y:238	width:486	height:381}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0019.png
	1: [{"label": ... ght:381}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0016.png,"[{""label"":""cookie"",type:""rectangle"",coordinates:{""x"":406	y:221	width:787	height:401}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0016.png
	1: [{"label": ... ght:401}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0028.png,"[{""label"":""croissant"",type:""rectangle"",coordinates:{""x"":191	y:124	width:144	height:115}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0028.png
	1: [{"label": ... ght:115}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0024.png,"[{""label"":""cookie"",type:""rectangle"",coordinates:{""x"":283	y:137	width:321	height:264}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0024.png
	1: [{"label": ... ght:264}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0023.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":556		y:378	width:638	height:620}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0023.png
	1: [{"label": ... ght:620}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0021.png,"[{""label"":""cookie"",type:""rectangle"",coordinates:{""x"":484	y:275	width:946	height:475}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0021.png
	1: [{"label": ... ght:475}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0022.png,"[{""label"":""croissant"",type:""rectangle"",coordinates:{""x"":463,y:303	width:515	height:406}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0022.png
	1: [{"label": ... ght:406}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0025.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":516		y:337	width:466	height:477}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0025.png
	1: [{"label": ... ght:477}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0026.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":522		y:420	width:625	height:721}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0026.png
	1: [{"label": ... ght:721}}]
13 lines failed to parse correctly
Finished parsing file /Users/matthew/annotations/annotations.csv
Parsing completed. Parsed 0 lines in 0.006869 secs.
Materializing SFrame
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-fbc50e139841> in <module>
----> 1 annotations.explore()

~/anaconda2/envs/TimApple/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in explore(self, title)
   4490         if title is None:
   4491             title = ""
-> 4492         self.__proxy__.explore(path_to_client, title)
   4493 
   4494     def show(self):

turicreate/_cython/cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.explore()

turicreate/_cython/cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.explore()

RuntimeError: Nothing to explore; SFrame is empty.

**Comment by MatthewGCampbell** [comment] 2019-07-24 18:36
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0025.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":516		y:337	width:466	height:477}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0025.png
	1: [{"label": ... ht":477}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0023.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":556		y:378	width:638	height:620}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0023.png
	1: [{"label": ... ht":620}}]
13 lines failed to parse correctly
Finished parsing file /Users/matthew/annotations/annotations.csv
Parsing completed. Parsed 0 lines in 0.029099 secs.
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0015.png,"[{""label"":""cookie"",type:""rectangle"",coordinates:{""x"":1938	y:1302	width:3434	height:2393}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0015.png
	1: [{"label": ... ht:2393}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0018.png,"[{""label"":""croissant"",type:""rectangle"",coordinates:{""x"":312	y:233	width:539	height:427}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0018.png
	1: [{"label": ... ght:427}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0017.png,"[{""label"":""croiss"",type:""rectangle"",coordinates:{""x"":370	y:640	width:631	height:368}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0017.png
	1: [{"label": ... ght:368}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0020.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":528		y:495	width:1009	height:920}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0020.png
	1: [{"label": ... ght:920}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0019.png,"[{""label"":""croissant"",type:""rectangle"",coordinates:{""x"":330	y:238	width:486	height:381}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0019.png
	1: [{"label": ... ght:381}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0016.png,"[{""label"":""cookie"",type:""rectangle"",coordinates:{""x"":406	y:221	width:787	height:401}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0016.png
	1: [{"label": ... ght:401}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0028.png,"[{""label"":""croissant"",type:""rectangle"",coordinates:{""x"":191	y:124	width:144	height:115}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0028.png
	1: [{"label": ... ght:115}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0024.png,"[{""label"":""cookie"",type:""rectangle"",coordinates:{""x"":283	y:137	width:321	height:264}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0024.png
	1: [{"label": ... ght:264}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0023.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":556		y:378	width:638	height:620}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0023.png
	1: [{"label": ... ght:620}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0021.png,"[{""label"":""cookie"",type:""rectangle"",coordinates:{""x"":484	y:275	width:946	height:475}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0021.png
	1: [{"label": ... ght:475}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0022.png,"[{""label"":""croissant"",type:""rectangle"",coordinates:{""x"":463,y:303	width:515	height:406}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0022.png
	1: [{"label": ... ght:406}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0025.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":516		y:337	width:466	height:477}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0025.png
	1: [{"label": ... ght:477}}]
Unexpected characters after last column. ""
Parse failed at token ending at: 
	data/Image0026.png,"[{""label"":""egg"",type:""rectangle"",coordinates:{""x"":522		y:420	width:625	height:721}}]",[1;31m^[0m
Successfully parsed 2 tokens: 
	0: data/Image0026.png
	1: [{"label": ... ght:721}}]
13 lines failed to parse correctly
Finished parsing file /Users/matthew/annotations/annotations.csv
Parsing completed. Parsed 0 lines in 0.006869 secs.
Materializing SFrame
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-fbc50e139841> in <module>
----> 1 annotations.explore()

~/anaconda2/envs/TimApple/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in explore(self, title)
   4490         if title is None:
   4491             title = ""
-> 4492         self.__proxy__.explore(path_to_client, title)
   4493 
   4494     def show(self):

turicreate/_cython/cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.explore()

turicreate/_cython/cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.explore()

RuntimeError: Nothing to explore; SFrame is empty.

**Comment by MatthewGCampbell** [comment] 2019-07-24 18:39
here is my error code

[](https://1drv.ms/w/s!AuEogTtHG6RcpGlIFCZ6_b3Y8ma_)

**Comment by MatthewGCampbell** [comment] 2019-07-24 18:40
https://1drv.ms/w/s!AuEogTtHG6RcpGlIFCZ6_b3Y8ma_

**Comment by MatthewGCampbell** [comment] 2019-07-24 18:40
there's my error code

**Comment by MatthewGCampbell** [comment] 2019-07-24 18:40
https://onedrive.live.com/view.aspx?resid=5CA41B473B8128E1!4713&ithint=file%2cdocx&authkey=!AEgUJnr9vdjyZr8

**Comment by znation** [comment] 2019-07-24 18:48
@MatthewGCampbell It looks like it's failing to parse some weird characters in your CSV file: `,[1;31m^[0m`. Is it possible it's a corrupted download, bad copy/paste, etc.? Are you able to open this CSV file and have it parsed properly in any spreadsheet application, like Excel, Numbers, etc.?

**Comment by MatthewGCampbell** [comment] 2019-07-24 18:55
@znation did you recieve my email? and I got it to work on my MacBook Air with the same file just not on my MacBook Pro ill send you a Excel screenshot

**Comment by MatthewGCampbell** [comment] 2019-07-24 18:56
<img width="985" alt="Screen Shot 2019-07-24 at 2 56 50 PM" src="https://user-images.githubusercontent.com/31420840/61820584-45d22880-ae23-11e9-8819-5d105d13437a.png">

**Comment by znation** [comment] 2019-07-24 20:05
Hi @MatthewGCampbell From the screenshot, the CSV file itself looks fine. Could you share the CSV file with us (either in this thread, or over email) and we can help diagnose the issue?

**Comment by MatthewGCampbell** [comment] 2019-07-24 20:36
Sorry I’m fixing one issue at a time right after I took the screenshot I saved it through excel and now it seems to work fine! But my next problem it that I created the model but can’t seem to find it on my computer, yeah I’d be happy to email it’s more simple than using github my email is: matthewgcampbell@icloud.com

**Comment by MatthewGCampbell** [comment] 2019-07-24 20:42
Is their like a default file name or place that it could be located

**Comment by znation** [comment] 2019-07-24 20:59
@MatthewGCampbell Once you have a model in Python, you would assign it to a variable like:

```python
model = tc.classifier.create(...)
```

Then, once it's in a model variable, you can save it to disk or export it for use with CoreML. You must explicitly determine the path in both cases. If you don't call `save` or `export_coreml`, your model will not be saved to disk at all.

```python
model.save('path/to/turicreate_model') # saves in Turi Create model format
model.export_coreml('path/to/model.mlmodel') # exports in Core ML model format
```

Hope that helps!

**Comment by MatthewGCampbell** [comment] 2019-07-24 21:08
Thanks I don’t remember what code I ran and don’t have access to my laptop cause I’m n my car but I ran something like model = tc.classifier.create(...) but I replaced the ... with data so after I run that command it gave me this https://share.icloud.com/photos/0fdoKoY8K3armb5jsRwqhK66A and after I run that command would I have to run the model.save command and the model export one too?

**Comment by MatthewGCampbell** [comment] 2019-07-24 21:09
Which email is best for you could you send me an email from that address? since I usually don’t check github and the easiest way for me is email and I respond quicker to my email.

**Comment by znation** [comment] 2019-07-24 21:12
@MatthewGCampbell It's better to keep issues on GitHub, as that way the rest of the community can keep aware of what issues we're having, weigh in on possible fixes and workarounds, and provide more information when they are also able to reproduce the issue. If you're having trouble getting notifications from GitHub over email, see [this article](https://help.github.com/en/articles/choosing-the-delivery-method-for-your-notifications) on how to configure notifications.

I think the answer to your latest question is, yes, you would need to call `save` and/or `export_coreml` after the `create` command. Depending on how you want to preserve the model artifact to disk and where you intend to use it, one or the other or both could make sense. `save` will save a model that is loadable in Turi Create (but not Core ML directly), and `export_coreml` will save a model that is loadable in Core ML (but not Turi Create).

**Comment by MatthewGCampbell** [comment] 2019-07-24 21:21
So then could I run both? Makes since to keep it in github tho.

**Comment by znation** [comment] 2019-07-24 23:25
@MatthewGCampbell Sure, you can run both. They will produce different file formats. The `save` method produces a Turi Create-compatible model in a directory structure. The `export_coreml` method produces a Core ML model in the .mlmodel file format.

**Comment by MatthewGCampbell** [comment] 2019-07-25 00:17
![Screen Shot 2019-07-24 at 8 17 36 PM](https://user-images.githubusercontent.com/31420840/61836835-15ed4a00-ae50-11e9-8239-0f67b495620e.png)
here is the command I ran for the model

**Comment by MatthewGCampbell** [comment] 2019-07-25 00:20
im a high school student and I'm going to a swift developing summer camp and the directors were asking if next year you would mind being a guest speaker? that's why I needed your email if you can't then no problem

**Comment by MatthewGCampbell** [comment] 2019-07-25 00:25
![Screen Shot 2019-07-24 at 8 23 54 PM](https://user-images.githubusercontent.com/31420840/61837044-fc003700-ae50-11e9-8960-3104efb86db5.png)
The model.save and the model.export_coreml commands don't seem to work not sure why? do the files already have to exist or is it creating a new file?

**Comment by TobyRoseman** [comment] 2019-07-25 00:29
When you seen `In [ * ]:` next to the code input box that means it's still working. When it's done the `*` will be replaced by a number.

**Comment by MatthewGCampbell** [comment] 2019-07-25 00:33
![Screen Shot 2019-07-24 at 8 32 38 PM](https://user-images.githubusercontent.com/31420840/61837306-2f8f9100-ae52-11e9-873a-94c2c7e0731c.png)
if I call it model 1 in the tc.object_detector.create command does it need to bet called model 1 for the rest of the code?

**Comment by MatthewGCampbell** [comment] 2019-07-25 00:33
bet = be

**Comment by MatthewGCampbell** [comment] 2019-07-25 00:52
![Screen Shot 2019-07-24 at 8 52 36 PM](https://user-images.githubusercontent.com/31420840/61837935-f99fdc00-ae54-11e9-8783-b57439b5c8e9.png)
still can't get it to work

**Comment by MatthewGCampbell** [comment] 2019-07-25 00:57
![Screen Shot 2019-07-24 at 8 56 13 PM](https://user-images.githubusercontent.com/31420840/61838047-7df25f00-ae55-11e9-91cb-ed4f74212a94.png)
Got it to work finally now can you just import the ml file
![Screen Shot 2019-07-24 at 8 57 12 PM](https://user-images.githubusercontent.com/31420840/61838062-9cf0f100-ae55-11e9-95e7-c9d2b20c7627.png)

**Comment by MatthewGCampbell** [comment] 2019-07-25 13:34
<img width="1190" alt="Screen Shot 2019-07-25 at 9 33 33 AM" src="https://user-images.githubusercontent.com/31420840/61878581-46b89800-aebf-11e9-8ada-987df3bd0cba.png">
trying to run this stuff from your WWDC talk when running the SFrame command how do I create the file with the images that it predicts?

**Comment by MatthewGCampbell** [comment] 2019-07-25 14:10
<img width="1504" alt="Screen Shot 2019-07-25 at 10 10 11 AM" src="https://user-images.githubusercontent.com/31420840/61881325-70c08900-aec4-11e9-97fa-c567867619d5.png">
what kind of a file is the .sframe? how do you make it?

**Comment by TobyRoseman** [comment] 2019-07-25 17:27
Please study the [Introduction to SFrames](https://apple.github.io/turicreate/docs/userguide/sframe/sframe-intro.html) and [Object Detection](https://apple.github.io/turicreate/docs/userguide/object_detection/) section of the user guide.

Since the original issues have been resolved I'm going to close this issue. If you have additional questions after studying our user guide, open a new issue.

**Closed by TobyRoseman** 2019-07-25 17:27 UTC
Labels: question

**Comment by MatthewGCampbell** [comment] 2019-07-25 17:31
Thanks so much for your help
