### ISSUE TITLE
> Hi @elseagle

### ISSUE THREAD

**Issue by dyaneshwer** [apple/turicreate#3317] opened 2020-09-07 15:35 UTC
> Hi @elseagle 
hey i am getting os error . i am using turicreate in window having ubuntu=18.04 Lts . when i try to import SFrame i got this error help me

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in __init__(self, data, format, _proxy)
    834                     url = _make_internal_url(data)
--> 835                     self.__proxy__.load_from_sframe_index(url)
    836                 elif _format == "empty":

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_sframe_index()

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_sframe_index()

OSError: /home/raj/E:/work/ml_assignment4/song_data.sframe not found. ErrMsg: file not exist in /home/raj/E:/work/ml_assignment4/song_data.sframe

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-2-ea10cb95d86f> in <module>
----> 1 sf = turicreate.SFrame("E:\work\ml_assignment4\song_data.sframe")

~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in __init__(self, data, format, _proxy)
    837                     pass
    838                 else:
--> 839                     raise ValueError("Unknown input type: " + format)
    840 
    841     @staticmethod

~/venv/lib/python3.6/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     48             if not self.show_cython_trace:
     49                 # To hide cython trace, we re-raise from here
---> 50                 raise exc_type(exc_value)
     51             else:
     52                 # To show the full trace, we do nothing and let exception propagate

OSError: /home/raj/E:/work/ml_assignment4/song_data.sframe not found. ErrMsg: file not exist in /home/raj/E:/work/ml_assignment4/song_data.sframe

_Originally posted by @raj9650sahni in https://github.com/apple/turicreate/issues/191#issuecomment-662375859_

**Comment by TobyRoseman** [comment] 2020-09-08 18:30
Based on the error and stack trace, I do not believe this is caused by trying to import TuriCreate. It looks like TuriCreate was successfully imported and this error was generated by trying to load a saved SFrame.

It looks like the path to the SFrame is wrong. It's trying to load an SFrame from: `/home/raj/E:/work/ml_assignment4/song_data.sframe`. Please check your path.

I'm going to close this issue, but let me know if you have additional questions or problems.

**Closed by TobyRoseman** 2020-09-08 18:30 UTC
