### ISSUE TITLE
Linux (Ubuntu) Error: Bus error at line: "import turicreate as tc"

### ISSUE THREAD

**Issue by THEDFG** [apple/turicreate#850] opened 2018-07-15 06:13 UTC
```
(venv) user@linux:~/stml$ python styleTransfer.py 
#import turicreate as tc
Bus error
```

**Comment by znation** [comment] 2018-07-16 23:30
Hi @THEDFG, could you please provide steps to reproduce this issue? As it is, most Linux users are able to successfully `import turicreate` - and I haven't seen this `Bus error` before.

**Comment by THEDFG** [comment] 2018-07-17 06:47
Hi @znation,

DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

https://mega.nz/#!3MUGTAxL!FOHeBfSe7CmhnTl7CXM_uMmYemqruWJ6nE5Q70nsick

**Comment by znation** [comment] 2018-07-17 21:53
Hi @THEDFG, I've been generally able to run turicreate successfully on Ubuntu 16.04.3 LTS. I can't tell what the contents of that link are that you provided; I see a disk image, but it doesn't appear to be something usable on my machine. Please provide specific repro steps that I can perform to reproduce the issue locally, including installation (if necessary) of common off-the-shelf operating systems as needed. Again, in general though, I am not able to reproduce this issue in Ubuntu 16.04 LTS.

**Comment by znation** [comment] 2018-07-18 18:29
This may apparently repro on the Ubuntu-derived SimpleMiningOS, but not stock Ubuntu. Need to investigate.

**Comment by THEDFG** [comment] 2018-07-19 05:48
Thank you very much Zack. Meanwhile I will try to install an official Ubuntu version on a rig. 

Best regards,
Gabriel Dana

**Comment by TobyRoseman** [comment] 2019-12-10 00:14
Closing this issue.

@THEDFG - please reopen if this is still an issue.

**Closed by TobyRoseman** 2019-12-10 00:14 UTC
Labels: bug, engine, p4
