### ISSUE TITLE
Terminal hangs when training 10 classes of 60 images

### ISSUE THREAD

**Issue by apoorvbagla** [apple/turicreate#519] opened 2018-04-12 09:23 UTC
Successfully trained 5 classes butTerminal hangs when training 10 classes of 60 images

**Comment by TobyRoseman** [comment] 2018-04-12 17:44
@apoorvbagla - What toolkit are you using, image classification, image similarity, object detection, or something else? How much RAM do you have?

**Comment by apoorvbagla** [comment] 2018-04-13 04:16
Im using **image classification** tool. Im running the python code on MacOS High Sierra with **8GB RAM**

This is the code Im running for preprocessing the data to create SFrame data which works fine for any size of data
 
import turicreate as tc
from turicreate import SFrame
from turicreate import SArray
import pandas as pd
import os

pathToImages = 'Images'
tempObjectLabel = []
files = os.listdir(pathToImages)
for file in files:
	tempObjectLabel.append(file)

objectLabel = tempObjectLabel[1:]

# Load images
data = tc.image_analysis.load_images(pathToImages, with_path=True)
# data = data.add_row_number('row')
#csv = pd.read_csv('annotations.csv')

temp = []

for j, item in enumerate(data):
    temp.append(os.path.split(item['path'])[1])


label = []

for j, item in enumerate(data):
	a = os.path.split(item['path'])[0]
	b = os.path.split(a)[1]
	if b not in objectLabel:
		label.append('misc')
		continue
	for i in temp:
		if i == str(os.path.split(item['path'])[1]):
			a = os.path.split(item['path'])[0]
			b = os.path.split(a)[1]
			print(b)
			label.append(b)
			break

data['label'] = SArray(data=label, dtype=str)

# the data is in no particular order, so we have to loop it to match
# we also have the 'misc' images, which won't have an annotation, to skip

# Save the data for future use
data.save('training.sframe')

#data['image_with_ground_truth'] = tc.object_detector.util.draw_bounding_boxes(data["image"], data["annotations"])

# Explore interactively
data.explore()

This is the code to train the model which hangs in case of around 10 classes and gives Kill 9 error on large number of classes.

import turicreate as tc
data = tc.SFrame('training.sframe')

train_data, test_data = data.random_split(0.8)

model = tc.image_classifier.create(train_data, target='label', max_iterations=2000)

model.save('mymodel.model')

model.export_coreml('MyCustomModel.mlmodel')

**Comment by TobyRoseman** [comment] 2018-04-13 17:01
@apoorvbagla - Thanks for sharing the code. I'm sorry you are having this issue. It is likely the same problem as #419

**Comment by fabriciorod** [comment] 2018-04-13 18:45
I'm having the same issue I have 21 classes with 20 images inside "images" folder, the ram usage increases until the system hangs.
is there any workaround? I tried using squeezenet but it doesn't work. 
```
import turicreate as tc

# Load images (Note: you can ignore 'Not a JPEG file' errors)
data = tc.image_analysis.load_images('images', with_path=True)

# From the path-name, create a label column
data['label'] = data['path'].apply(lambda path: path.split('/')[-2])

print(data['label'])
# Save the data for future use
data.save('persons.sframe')

# Explore interactively
# data.explore()

result_data = tc.SFrame('persons.sframe')

train_data, test_data = result_data.random_split(0.8)

model = tc.image_classifier.create(train_data, target='label', model='resnet-50', max_iterations=15, verbose=True)

# Save the model for later use in Turi Create
print('saving model')
model.save('persons.model')

print('saving coreml model')
model.export_coreml('persons.mlmodel')
```
Thanks for this amazing project by the way.

**Comment by TobyRoseman** [comment] 2018-04-14 04:55
@fabriciorod - I put up [a fix](https://github.com/apple/turicreate/pull/531/commits/323bcdff4ff84a7d49ad144e7f92804841111765) for this issue. Give that a try.

**Comment by srikris** [comment] 2018-04-14 05:10
@fabriciorod While this fix lands soon, a quick way to unblock you is to use turicreate==4.1. We've traced down the regression to something introduced in 4.2.

**Comment by fabriciorod** [comment] 2018-04-14 17:45
Thanks @srikris @TobyRoseman I'll give that a try.

**Comment by znation** [comment] 2018-04-14 18:43
Dupe of #419.

**Closed by znation** 2018-04-14 18:43 UTC
Labels: bug, duplicate

**Comment by apoorvbagla** [comment] 2018-04-16 08:55
Thanks for the fix, it works fine now

**Comment by jaskierLTD** [comment] 2018-07-08 12:07
No. I have -kill9 after 34 hours of waiting...
25000+ images, 266 + categories ...
Mac OS Mojave, res-net50. The error occurs only after all calculations.
![screenshot 2018-07-08 at 13 49 31](https://user-images.githubusercontent.com/35968129/42419572-2d62f140-82b8-11e8-8241-0b7d081f6984.png)
![screenshot 2018-07-08 at 13 49 57](https://user-images.githubusercontent.com/35968129/42419574-309796e0-82b8-11e8-8bde-0f86986fef89.png)
![screenshot 2018-07-08 at 14 04 43](https://user-images.githubusercontent.com/35968129/42419577-32634898-82b8-11e8-9afb-b4fd81f83792.png)

**Comment by jaskierLTD** [comment] 2018-07-08 12:08
Could someone, please help me to train the model? 
jaskierLTD@gmail.com
Telegram: +380 66 519 66 27

**Comment by TobyRoseman** [comment] 2018-07-09 17:51
@jaskierLTD - What version of Turi Create are you using? If you are not running the 5.0 beta, please follow [the instructions to install it](https://github.com/apple/turicreate#version-50-beta).

**Comment by jaskierLTD** [comment] 2018-07-09 17:54
Thank you !)
