### ISSUE TITLE
What tools are used to mark data

### ISSUE THREAD

**Issue by baihualinxin** [apple/turicreate#852] opened 2018-07-16 06:30 UTC
already have a data model and you need to tag the data。
What tools do you use??
turicreate-master/src/visualization/Turi Create Visualization 
Turi Create Visualization How do you use it?

How do I use marked data? Please correct class labels and border boxes for each instance

**Comment by TobyRoseman** [comment] 2018-07-16 19:07
Duplicate of #828

**Closed by TobyRoseman** 2018-07-16 19:07 UTC
Labels: duplicate, feature request
