### ISSUE TITLE
Change visualization.categorical_heatmap algorithm?

### ISSUE THREAD

**Issue by kuri54** [apple/turicreate#2463] opened 2019-10-17 09:52 UTC
Has the "visualization.categorical_heatmap" generation algorithm changed from Turicreate5.8?

<img width="729" alt="5 6-1" src="https://user-images.githubusercontent.com/40049003/66998610-83d3a580-f10f-11e9-9d1c-2804d5d3afc5.png">
<img width="733" alt="5 8-1" src="https://user-images.githubusercontent.com/40049003/66998616-8504d280-f10f-11e9-9608-bf61d5f17253.png">
<img width="752" alt="5 6-2" src="https://user-images.githubusercontent.com/40049003/66998621-86ce9600-f10f-11e9-95e4-ac0d57efee1e.png">
<img width="737" alt="5 8-2" src="https://user-images.githubusercontent.com/40049003/66998624-87ffc300-f10f-11e9-84f8-2d9cddb780b7.png">

**Comment by TobyRoseman** [comment] 2019-10-17 18:21
Hi @kuri54 - Please provide a few more details here. It would be helpful if you could share the following information:

1 - Are you just curious if there has been a change, or do you think there is some sort of bug or degradation? If so, what is the bug/degradation?
2 - Can you share a simple example (i.e. code + data) to generate charts like the ones you shared?

**Comment by kuri54** [comment] 2019-10-17 22:57
I think it's a bug.
Obviously the color is different and the generated image is a little different.

If it's a silent fix, that's fine, but I want to know if there is any intentional fix.

Since I am actually using this heat map in my research, I am worried about whether to correct all the data.

You can't get a simple example right away, so please refer to the official API ...

**Comment by TobyRoseman** [comment] 2019-10-18 00:26
@kuri54 - I don't think anything has changed with the heat map. Looking at our [release notes](https://github.com/apple/turicreate/releases), I don't see anything that look relevant for `5.7`, `5.7.1` or `5.8`.

Yes, the colors are different. I'm not sure that's a sign of a bug.

**Comment by znation** [comment] 2019-10-18 00:41
@kuri54 Other than the colors changing, I don't see any other differences here. My interpretations of the charts are (and correct me if I'm wrong):

* The first chart shows 10 true positive examples in both 5.6 and 5.8.
* The second chart shows 9 true positives and one false positive, in both 5.6 and 5.8.

It's not clear to me that the 5.6 renderings are in any way more "correct" than 5.8; though the color scheme change was unintentional and likely came with a dependency version upgrade, I'm not seeing any incorrect information showing in either version.

**Comment by kuri54** [comment] 2019-10-18 01:05
I'm sorry for my poor English. The explanation was not good.

This time I felt the problem was that the color and the scale at the top of the graph were different.

The numbers in the generated graph are very accurate and are not considered a problem.

At the same time, with the upgrade of Turicreate, the OS was changed to Catalina. To be honest, I don't have a clue where the color problem is due.

However, it is certain that the scale of the generated graph is different.

**Comment by znation** [comment] 2019-10-18 01:20
Hi @kuri54, I think I know what may have caused it. We [upgraded our dependency version](https://github.com/apple/turicreate/pull/2152) of [Vega](https://vega.github.io) (the visualization library we use) and it seems that the default color palette(s) changed between versions. Since the new one looks at least as good to me as the old one, I wouldn't consider this a bug. Would you mind explaining why you think the change in color palette is a problem?

If you want color consistency in your visualizations, you may want to consider using an external charting library that gives you finer control over how things are visualized (for instance, you could use [to_dataframe](https://apple.github.io/turicreate/docs/api/generated/turicreate.SFrame.to_dataframe.html#turicreate.SFrame.to_dataframe) to convert to Pandas, then use [Altair](https://altair-viz.github.io) to visualize).

**Comment by znation** [comment] 2019-10-18 01:21
(Note that Altair uses Vega as well, so the same color palette changes may occur if the defaults change in between versions.)

**Comment by kuri54** [comment] 2019-10-18 05:22
So that's it.

It was very rough to describe it as a bug. I'm sorry.

I couldn't publicize the research, but I was thinking of making a machine learning model using the generated heat map. To that end, I thought that the format of the heat map, including the colors, had to be unified.

However, these were only for my convenience.

**Comment by znation** [comment] 2019-10-18 05:42
No worries @kuri54, thank you for explaining! Glad we were able to find the cause of the issue.

I suggest for future use of visualization in this manner, you may want to stick to a particular Turi Create version, as the visualizations may change (either because we have changed the design, or incidentally because we have changed the implementation). I will close this issue for now.

**Closed by znation** 2019-10-18 05:42 UTC
Labels: need user repro, visualization
