### ISSUE TITLE
Column type of target 'rating' must be int or str in sentence_classifier.create

### ISSUE THREAD

**Issue by Padalingam** [apple/turicreate#234] opened 2018-02-02 06:35 UTC
I got the following error, when i execute the sentence_classifier

Input csv is 

rating | text
-- | --
Positive | This movie is awesome
Positive | This movie is excellent
Positive | This movie is good
Positive | This movie is wonderful
Positive | This movie is ok
Negative | This movie is bad
Negative | This movie is not good
Negative | This movie is too bad
Positive | This movie is fantastic

i set all the two column type as text only.
classifier.py
import turicreate as tc
# Load data
data = tc.SFrame('ratings.csv')

# Create a model
model = tc.sentence_classifier.create(data, 'rating', features=['text'])

# Make predictions & evaluation the model
predictions = model.predict(data)
results = model.evaluate(data)

# Save the model for later use in Turi Create
model.save('MySentenceClassifier.model')

# Export for use in Core ML
model.export_coreml('MySentenceClassifier.mlmodel')

when run the python file, i got the following error

Finished parsing file /Users/padalingam/Documents/Xcode 9 Projects/MovieAnalysis/ratings.csv
Parsing completed. Parsed 9 lines in 0.038302 secs.
------------------------------------------------------
Inferred types from first 100 line(s) of file as 
column_type_hints=[str,str]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------
Finished parsing file /Users/padalingam/Documents/Xcode 9 Projects/MovieAnalysis/ratings.csv
Parsing completed. Parsed 9 lines in 0.009546 secs.
[ERROR] turicreate.toolkits._main: Toolkit error: Column type of target 'rating' must be int or str.

Traceback (most recent call last):
  File "classifier.py", line 6, in <module>
    model = tc.sentence_classifier.create(data, 'rating', features=['text'])
  File "/Library/Python/2.7/site-packages/turicreate/toolkits/sentence_classifier/_sentence_classifier.py", line 107, in create
    **kwargs)
  File "/Library/Python/2.7/site-packages/turicreate/toolkits/classifier/logistic_classifier.py", line 307, in create
    class_weights = class_weights)
  File "/Library/Python/2.7/site-packages/turicreate/toolkits/_supervised_learning.py", line 393, in create
    options, verbose)
  File "/Library/Python/2.7/site-packages/turicreate/toolkits/_main.py", line 84, in run
    raise ToolkitError(str(message))
turicreate.toolkits._main.ToolkitError: Column type of target 'rating' must be int or str.

**Comment by srikris** [comment] 2018-02-02 06:37
Thanks for trying out TC. This is a duplicate of #98. We are looking into it.

**Comment by Padalingam** [comment] 2018-02-02 06:38
Even, i used tc.SFrame.read_csv('ratings.csv') but the error remains same

**Comment by srikris** [comment] 2018-02-02 06:40
Looks like this is not a duplicate. Let me look into it.

**Comment by Padalingam** [comment] 2018-02-02 07:38
i have tried 
1) data = tc.SFrame.read_csv('ratings.csv', column_type_hints={'ratings':str, 'text':str})
2) data = tc.SFrame.read_csv('ratings.csv', column_type_hints=str)

But the error remains the same but if i try data = tc.SFrame({'rating': [1, 5], 'text': ['hate it', 'love it']})
this works fine

**Comment by srikris** [comment] 2018-02-02 07:39
Thanks for giving more info. I have traced the bug and made a fix. I'm testing it locally. I'll put up a PR soon.

**Comment by srikris** [comment] 2018-02-02 07:46
Fixed with #235. Version 4.1 is coming real soon.  Thanks for reporting.

**Comment by Padalingam** [comment] 2018-02-02 08:16
Thanks dude. How can i check my turicreate current version and how can update the new version?.

**Comment by srikris** [comment] 2018-02-02 08:23
When the new version comes out, it will have this bug fix and you can upgrade with 

```
pip install turicreate --upgrade
```

**Comment by Padalingam** [comment] 2018-02-02 08:37
Thanks. it's working for following data set

rating | text
-- | --
1 | This is too good
1 | This is too wonderful
1 | This is too awesome
1 | This is too good
1 | This is worth to watch
0 | This is too bad
0 | This is not good
0 | This is very bad
1 | This is fantastic

But, i got the following error
Traceback (most recent call last):
  File "classifier.py", line 17, in <module>
    model.export_coreml('MySentenceClassifier.mlmodel')
  File "/Library/Python/2.7/site-packages/turicreate/toolkits/_model.py", line 324, in __getattribute__
    return object.__getattribute__(self, attr)
AttributeError: 'SentenceClassifier' object has no attribute 'export_coreml'

**Comment by srikris** [comment] 2018-02-02 08:39
This is most definitely #98 :) which we are investigating

**Comment by Padalingam** [comment] 2018-02-02 08:44
But, this error is seems to be SentenceClassifier doesn't have the export_coreml method

**Comment by srikris** [comment] 2018-02-02 08:45
It has been added after 4.0 and will be available in 4.1. This should be available soon.

**Comment by Padalingam** [comment] 2018-02-02 08:49
Thanks bro

**Comment by srikris** [comment] 2018-02-02 21:34
Fixed.

**Closed** 2018-02-03 04:15 UTC

**Comment by Padalingam** [comment] 2018-02-03 04:27
After upgrade
Padalingam-MacBook-Pro:MovieAnalysis padalingam$ pip install turicreate --upgrade
Requirement already up-to-date: turicreate in /Library/Python/2.7/site-packages
Requirement already up-to-date: pillow>=3.3.0 in /Library/Python/2.7/site-packages (from turicreate)
Requirement already up-to-date: requests>=2.9.1 in /Library/Python/2.7/site-packages (from turicreate)
Requirement already up-to-date: pandas>=0.19.0 in /Library/Python/2.7/site-packages (from turicreate)
Requirement already up-to-date: coremltools==0.6.3 in /Library/Python/2.7/site-packages (from turicreate)
Requirement already up-to-date: decorator>=4.0.9 in /Library/Python/2.7/site-packages (from turicreate)
Requirement already up-to-date: prettytable==0.7.2 in /Library/Python/2.7/site-packages (from turicreate)
Requirement already up-to-date: mxnet==0.11 in /Library/Python/2.7/site-packages (from turicreate)
Requirement already up-to-date: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests>=2.9.1->turicreate)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests>=2.9.1->turicreate)
Requirement already up-to-date: idna<2.7,>=2.5 in /Library/Python/2.7/site-packages (from requests>=2.9.1->turicreate)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /Library/Python/2.7/site-packages (from requests>=2.9.1->turicreate)
Requirement already up-to-date: python-dateutil in /Library/Python/2.7/site-packages (from pandas>=0.19.0->turicreate)
Requirement already up-to-date: numpy>=1.9.0 in /Library/Python/2.7/site-packages (from pandas>=0.19.0->turicreate)
Requirement already up-to-date: pytz>=2011k in /Library/Python/2.7/site-packages (from pandas>=0.19.0->turicreate)
Requirement already up-to-date: protobuf>=3.1.0 in /Library/Python/2.7/site-packages (from coremltools==0.6.3->turicreate)
Requirement already up-to-date: six==1.10.0 in /Library/Python/2.7/site-packages (from coremltools==0.6.3->turicreate)
Requirement already up-to-date: graphviz in /Library/Python/2.7/site-packages (from mxnet==0.11->turicreate)
Requirement already up-to-date: setuptools in /Library/Python/2.7/site-packages (from protobuf>=3.1.0->coremltools==0.6.3->turicreate)

And still, i have the same issue

**Comment by Padalingam** [comment] 2018-02-03 04:29
i think, i am not able get a new version of turicreate. its working fine when rating column is a int

**Comment by srikris** [comment] 2018-02-03 04:36
As I made mentioned earlier, the new version is not yet released. It will be coming soon. We will post here when we upload the new version.

**Comment by afranklin** [comment] 2018-02-08 20:28
Turi Create 4.1 is now available.
