### ISSUE TITLE
Drawing Classifier API Breaking Change

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2646] opened 2019-11-15 23:38 UTC
Seems the drawing classifier’s create function no longer allows `validation_set=None` which is an API breaking change from 5.8.

**Comment by shantanuchhabra** [comment] 2019-11-16 02:38
Dupe of #2605, so closing this issue. PR is up at #2650

**Closed by shantanuchhabra** 2019-11-16 02:38 UTC
Labels: drawing classifier, duplicate
