### ISSUE TITLE
Remove PIL dependence in Image.save

### ISSUE THREAD

**Issue by gustavla** [apple/turicreate#715] opened 2018-06-18 23:27 UTC
The PIL dependency for `turicreate.Image.save` is easily avoidable, since we link with libpng/libjpeg and have a function on the C++ side already that save an image.

See more info here: https://github.com/apple/turicreate/pull/709#issuecomment-398225026

**Comment by znation** [comment] 2018-07-23 22:08
Dupe of #380.

**Closed by znation** 2018-07-23 22:08 UTC
Labels: 1807, cleanup, images, p3
