### ISSUE TITLE
Error while installing Turicreate in MacOS Big Sur 11.3.1

### ISSUE THREAD

**Issue by ArraryChen** [apple/turicreate#3429] opened 2021-11-02 13:21 UTC
MacOS Big Sur 11.3.1
The version of Python3 is 3.8.2
I have updated my pip and it shows Requirement already satisfied.
but while Im installing Turicreate and then show error. I feel so confused about that for a long time. ;(

The information of error below:
Defaulting to user installation because normal site-packages is not writeable
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-zzn3yfdw/turicreate_2180a0663ccc4091814a5575b36d1799/setup.py'"'"'; __file__='"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-zzn3yfdw/turicreate_2180a0663ccc4091814a5575b36d1799/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-wheel-i0_9pps7
       cwd: /private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-zzn3yfdw/turicreate_2180a0663ccc4091814a5575b36d1799/
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build/bdist.macosx-10.14.6-arm64/wheel
  running install
  
  
  
          ==================================================================================
          TURICREATE ERROR
  
          If you see this message, pip install did not find an available binary package
          for your system.
  
          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).
  
          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
              * 3.8
  
          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`
  
          ==================================================================================
  
  
  
  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-zzn3yfdw/turicreate_2180a0663ccc4091814a5575b36d1799/setup.py'"'"'; __file__='"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-zzn3yfdw/turicreate_2180a0663ccc4091814a5575b36d1799/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-record-07uqzkyy/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/jianie/Library/Python/3.8/include/python3.8/turicreate
         cwd: /private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-zzn3yfdw/turicreate_2180a0663ccc4091814a5575b36d1799/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
                * 3.8
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-zzn3yfdw/turicreate_2180a0663ccc4091814a5575b36d1799/setup.py'"'"'; __file__='"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-zzn3yfdw/turicreate_2180a0663ccc4091814a5575b36d1799/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-record-07uqzkyy/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/jianie/Library/Python/3.8/include/python3.8/turicreate Check the logs for full command output.

If u could help me solve this error, I will be appreciated.

**Comment by TobyRoseman** [comment] 2021-11-02 18:57
I'm not sure what is going on here. It looks like you are not using a virtual environment. I believe your issue is related to that. Using a virtual environment is recommend.

Follow the instruction in [the `Installation` section of our README](https://github.com/apple/turicreate#installation) to install with a virtual environment.

**Comment by ArraryChen** [comment] 2021-11-03 00:21
> I'm not sure what is going on here. It looks like you are not using a virtual environment. I believe your issue is related to that. Using a virtual environment is recommend.
> 
> Follow the instruction in [the `Installation` section of our README](https://github.com/apple/turicreate#installation) to install with a virtual environment.

Actually I have tried to use venv to install turicreate but also shows the same error.

**Comment by TobyRoseman** [comment] 2021-11-03 00:28
> Actually I have tried to use venv to install turicreate but also shows the same error.

Interesting. Try running `pip install wheel` then try running `pip install -U turicreate`.

**Comment by ArraryChen** [comment] 2021-11-03 00:46
> `pip install -U turicreate`.

as you see, it has the same error.

(venv) jianie@1999 ~ % pip install wheel
Collecting wheel
  Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.37.0
(venv) jianie@1999 ~ % pip install -U turicreate 
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/jianie/Desktop/MyFile/others/venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-3aor6bxi/turicreate_60e5b849118e4e2e8dc1d65b7ba1522b/setup.py'"'"'; __file__='"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-3aor6bxi/turicreate_60e5b849118e4e2e8dc1d65b7ba1522b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-wheel-u9alrpln
       cwd: /private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-3aor6bxi/turicreate_60e5b849118e4e2e8dc1d65b7ba1522b/
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build/bdist.macosx-10.14.6-arm64/wheel
  running install
  
  
  
          ==================================================================================
          TURICREATE ERROR
  
          If you see this message, pip install did not find an available binary package
          for your system.
  
          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).
  
          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
              * 3.8
  
          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`
  
          ==================================================================================
  
  
  
  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/jianie/Desktop/MyFile/others/venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-3aor6bxi/turicreate_60e5b849118e4e2e8dc1d65b7ba1522b/setup.py'"'"'; __file__='"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-3aor6bxi/turicreate_60e5b849118e4e2e8dc1d65b7ba1522b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-record-i9m3crq6/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jianie/Desktop/MyFile/others/venv/include/site/python3.8/turicreate
         cwd: /private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-3aor6bxi/turicreate_60e5b849118e4e2e8dc1d65b7ba1522b/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
                * 3.8
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/jianie/Desktop/MyFile/others/venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-3aor6bxi/turicreate_60e5b849118e4e2e8dc1d65b7ba1522b/setup.py'"'"'; __file__='"'"'/private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-install-3aor6bxi/turicreate_60e5b849118e4e2e8dc1d65b7ba1522b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c_/m27r_mn54qq53ld3dtfzqzmh0000gn/T/pip-record-i9m3crq6/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jianie/Desktop/MyFile/others/venv/include/site/python3.8/turicreate Check the logs for full command output.

**Comment by TobyRoseman** [comment] 2021-11-03 20:54
Can you share the output of running the following from the command line?
`uname -a`

**Comment by ArraryChen** [comment] 2021-11-04 01:03
> Can you share the output of running the following from the command line?
> `uname -a`

(venv) jianie@1999 ~ % uname -a
Darwin 1999 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64

**Comment by Enzo90910** [comment] 2021-11-04 18:00
Looks related to #3372

**Comment by TobyRoseman** [comment] 2021-11-04 18:33
@Enzo90910 is correct. TuriCreate does not have native support for M1.

@ArraryChen - If you want to use TuriCreate on an M1 machine, you need to use [Rosetta](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment).

Closing this as a duplicate of #3372.

**Closed by TobyRoseman** 2021-11-04 18:33 UTC

**Comment by ArraryChen** [comment] 2021-11-05 01:04
> @Enzo90910 is correct. TuriCreate does not have native support for M1.
> 
> @ArraryChen - If you want to use TuriCreate on an M1 machine, you need to use [Rosetta](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment).
> 
> Closing this as a duplicate of #3372.

Sorry, I'm a beginner about turicreate.
I'm current learning ML in cousera, the class asks me to install turicreate so that I can use some package to finish my assignment.
u has mentioned about Rosetta. But I don't know how to use rosetta in installing turicreate.

I'm afraid I will bother you about that.

**Comment by TobyRoseman** [comment] 2021-11-06 00:12
Open Finder and go to "Applications", then "Utilities". Make a copy of the "Terminal". Call your copy something like "Rosetta Terminal". Right click on it and select "Get Info". Click the checkbox which says "Open using Rosetta". Launch your Rosetta Terminal and install TuriCreate like you normally would.

**Comment by ArraryChen** [comment] 2021-11-06 04:18
> Open Finder and go to "Applications", then "Utilities". Make a copy of the "Terminal". Call your copy something like "Rosetta Terminal". Right click on it and select "Get Info". Click the checkbox which says "Open using Rosetta". Launch your Rosetta Terminal and install TuriCreate like you normally would.

it works, thank you very much.

**Comment by tungxd96** [comment] 2022-07-10 20:21
I'm still facing that error on M1 pro (MacOS Monterey 12.4) before/after trying Rosetta. Is there an alternative way?

**Comment by gauravnitb90** [comment] 2023-02-05 14:21
@TobyRoseman I am also facing error during turicreate install on Rosetta terminal on Mac M1. Python version is 3.7.
------------------------------
(base) gauravgu@Gauravs-MacBook-Pro-97 ML % uname -m                    
x86_64
(base) gauravgu@Gauravs-MacBook-Pro-97 ML % source venv/bin/activate
(venv) (base) gauravgu@Gauravs-MacBook-Pro-97 ML % pip install -U turicreate
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      running bdist_wheel
      running build
      /Users/gauravgu/Desktop/ML/venv/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      installing to build/bdist.macosx-12.5-arm64/wheel
      running install
      
      
      
              ==================================================================================
              TURICREATE ERROR
      
              If you see this message, pip install did not find an available binary package
              for your system.
      
              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).
      
              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8
      
              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`
      
              ==================================================================================
      
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
  Running setup.py install for turicreate ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for turicreate did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      running install
      /Users/gauravgu/Desktop/ML/venv/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      
      
      
              ==================================================================================
              TURICREATE ERROR
      
              If you see this message, pip install did not find an available binary package
              for your system.
      
              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).
      
              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8
      
              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`
      
              ==================================================================================
      
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> turicreate

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
(venv) (base) gauravgu@Gauravs-MacBook-Pro-97 ML % uname -a
Darwin Gauravs-MacBook-Pro-97.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 x86_64

----------
Could you please help me how to resolve this issue?

**Comment by gauravnitb90** [comment] 2023-02-05 15:36
It wasn't working for me until I used Anaconda x86_64.

**Comment by himbeles** [comment] 2023-02-15 09:09
Sidenote: you can use the last Python 3.8 Intel Installer https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg to install a turicreate compatible version of Python via Rosetta.
