### ISSUE TITLE
Object Detection performance issues with large images 

### ISSUE THREAD

**Issue by michaelschleiss** [apple/turicreate#224] opened 2018-01-29 20:25 UTC
I am training the object detector on a dataset with large images 3000x2000 pixels on a GPU. I couldn't see any difference in the time that is spent on training compared between training on GPU or CPU. 

I made that training on GPU is set to active and it works fine for the sample image classification task with the dogs and cats. There I see a huge performance difference between GPU or CPU. 

But for my custom dataset it is very slow. Is there a fix for this? My intuition would be that it takes too much time to load images into memory. Could this some how be sped up?

**Comment by gustavla** [comment] 2018-01-29 21:17
There are known performance issues for running the detector on large images, and you are probably spending a lot of time resizing the images down to the size expected by the neural network. This issue is tracked in #139, which also contains some work-arounds (such as resizing them in the SFrame).

Also, you could you try running your creation script like this:

```
MXNET_CPU_WORKER_NTHREADS=8 python create_object_detector.py
```
I'm curious to hear if this makes a difference. The image resizing always occurs on the CPU, and this will allow more CPU threads to be used to perform the task.

**Comment by srikris** [comment] 2018-02-02 07:47
Dupe of #139

**Closed by srikris** 2018-02-02 07:47 UTC
