### ISSUE TITLE
Support for custom aggregation functions

### ISSUE THREAD

**Issue by syoutsey** [apple/turicreate#2281] opened 2019-09-05 17:11 UTC
Turi Create offers an [aggregate method](https://apple.github.io/turicreate/docs/api/generated/turicreate.aggregate.html) with a number of predefined operators. This issue is to track support for custom aggregators outside of the ones defined by Turi Create.

**Comment by TobyRoseman** [comment] 2020-09-01 20:58
This is a duplicate of #1071.

**Closed by TobyRoseman** 2020-09-01 20:58 UTC
Labels: duplicate, engine, enhancement
