### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by Rhutus** [apple/turicreate#2734] opened 2019-11-22 05:20 UTC

**Comment by TobyRoseman** [comment] 2019-11-22 05:43
@Rhutus - Please include the full output you get when you try to pip install. Also please let us know your version of Python and your operating system.

**Comment by Rhutus** [comment] 2019-11-22 05:55
> @Rhutus - Please include the full output you get when you try to pip install. Also please let us know your version of Python and your operating system.

Full Output:
ERROR: Command errored out with exit status 1:
     command: /home/anaconda3/envs/virtual_environment_name/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-htv5zwat/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-htv5zwat/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-htv5zwat/turicreate/pip-egg-info
         cwd: /tmp/pip-install-htv5zwat/turicreate/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/anaconda3/envs/virtual_environment_name/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-htv5zwat/turicreate/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Here is Version: Python 3.7.4
ubuntu 16.04 LTS

**Comment by srikris** [comment] 2019-11-22 05:55
Dupe of #788. This is coming soon in 6.0!

**Closed by srikris** 2019-11-22 05:55 UTC
Labels: need user repro, setup
