### ISSUE TITLE
Each iteration took different amount of time depending on `max_iterations` in Style Transfer

### ISSUE THREAD

**Issue by yhoonkim** [apple/turicreate#760] opened 2018-06-25 22:16 UTC
I trained a style transfer model with one content and one style.
Without setting `max_iterations`(or explicitly setting as 5000), it took about 30s per each iteration. 
```
Using 'image' in style_dataset as feature column and using 'image' in content_dataset as feature column
Setting max_iterations to be 5000
Using CPU to create model
Analyzing visual features of the style images
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 8.172        | 8.7          |
| 2            | 8.166        | 36.1         |
| 3            | 8.154        | 64.3         |
| 4            | 8.137        | 95.4         |
| 5            | 8.116        | 124.8        |
| 6            | 8.091        | 152.9        |
| 7            | 8.063        | 181.7        |
| 8            | 8.032        | 210.8        |
| 9            | 7.999        | 238.2        |
```
However, when I set it as 5, the first iteration took 30s, and I couldn't get a response of the second iteration for 10 minutes. (I stopped the run after then.)
```python
model = tc.style_transfer.create(styles, content, max_iterations=5 ) # 2:43PM
# No response @ 2:53PM
```
```
Using 'image' in style_dataset as feature column and using 'image' in content_dataset as feature column
Using CPU to create model
Analyzing visual features of the style images
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 8.172        | 31.4         |
```

I think the user usually set the` max_interaction` to control the amount of time to train with expecting the same (similar) amount of time per iteration. The attached is the images I used for the style and the content. 

## Content
<img width="224" alt="cat" src="https://user-images.githubusercontent.com/6269456/41878628-a955e16e-788a-11e8-983e-d82a80b6c542.png">

## Style
![style](https://user-images.githubusercontent.com/6269456/41878629-a987209e-788a-11e8-9690-f74b861c28e6.jpg)

**Comment by xumeng723** [comment] 2018-07-12 08:18
I met the same problem as you, after testing, I believe that it is because the function tc.style_transfer.create has no parameter of max iterations,or not the same order. But I have no answer now.

**Comment by enzyme69** [comment] 2018-07-12 14:35
You need to have more contents images, minimum 4, I think.

Similar "bug" I was experiencing:
https://github.com/apple/turicreate/issues/636

PS: I still cannot get style that is more VGG, too much Resnet at the moment...

**Comment by shreyasvj25** [comment] 2018-08-03 18:20
Dupe of #636

**Closed by shreyasvj25** 2018-08-03 18:20 UTC
Labels: bug, duplicate, p2, style transfer
