### ISSUE TITLE
Object detection - Got mxnet error When start training @ CPU & GPU

### ISSUE THREAD

**Issue by dhgokul** [apple/turicreate#1124] opened 2018-10-04 10:30 UTC
@srikris I got error when start the training - PFA 

![image](https://user-images.githubusercontent.com/5689804/46468539-5232b980-c7ee-11e8-8474-02837d042f0e.png)

**Comment by dhgokul** [comment] 2018-10-08 10:40
@srikris Any update on this issue ?

**Comment by cianiandreadev** [comment] 2018-10-08 12:16
Never seen this issue. Have you tried to run it on Python 3.6? Could be that this doesn't help, but, if it's easy for you to switch could worth a try.

**Comment by srikris** [comment] 2018-10-08 19:57
@dhgokul: Can you give us some info about what version of MXNet you are using and what CUDA you have installed on the machine?

**Comment by dhgokul** [comment] 2018-10-09 05:40
MXnet cuda 1.1.0 and cuda 9. After remove some PNG image . Issue got resolved

**Comment by dhgokul** [comment] 2018-10-09 05:42
@srikris Any ways to print out image name which occur issue ? It would be more helpful for us !

**Comment by srikris** [comment] 2018-10-10 16:03
Can you share the PNG that caused the issue. I suspect it might be a grayscale image.

**Comment by nickjong** [comment] 2018-11-14 20:19
Based on the backtrace, this is a dupe of #1046, caused either by a RGBA PNG image or a CMYK JPEG. With the fix for that bug, we'll convert 4-channel PNG appropriately, but libjpeg doesn't support CMYK -> RGB

**Closed by nickjong** 2018-11-14 20:19 UTC
Labels: bug, p1, toolkits
