### ISSUE TITLE
Linux styleTransfer mxnet-cu92==1.2.1 MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by THEDFG** [apple/turicreate#896] opened 2018-07-25 21:40 UTC
```
(venv) ~/Desktop/turi/styleTransfer$ pip freeze | grep mxnet
mxnet==1.1.0.post0
mxnet-cu92==1.2.1
(venv) ~/Desktop/turi/styleTransfer$ 
(venv) ~/Desktop/turi/styleTransfer$ python styleTransfer.py 
WARNING: You are using MXNet 1.2.1 which may result in breaking behavior.
         To fix this, please install the currently recommended version:

             pip uninstall -y mxnet && pip install mxnet==1.1.0

         If you want to use a CUDA GPU, then change 'mxnet' to 'mxnet-cu90' (adjust 'cu90' depending on your CUDA version):

Unsupported image format. Supported formats are JPEG and PNG   file: style/.DS_Store
Read 248 images in 5.05523 secs speed: 49.0581 file/sec
Read 296 images in 10.09 secs speed: 9.53371 file/sec
Using 'image' in style_dataset as feature column and using 'image' in content_dataset as feature column
Traceback (most recent call last):
  File "styleTransfer.py", line 21, in <module>
    model = tc.style_transfer.create(styles, content, max_iterations=1000)
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/toolkits/style_transfer/style_transfer.py", line 192, in create
    sequential=params['sequential_image_processing'])
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/toolkits/style_transfer/_sframe_loader.py", line 101, in __init__
    self.sframe[_TMP_COL_PREP_IMAGE] = self.sframe[self.feature_column].apply(img_prep_fn)
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/data_structures/sarray.py", line 1892, in apply
    dryrun = [fn(i) for i in self.head(100) if i is not None]
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/data_structures/sarray.py", line 802, in generator
    self.__proxy__.begin_iterator()
  File "turicreate/cython/cy_sarray.pyx", line 270, in turicreate.cython.cy_sarray.UnitySArrayProxy.begin_iterator
  File "turicreate/cython/cy_sarray.pyx", line 271, in turicreate.cython.cy_sarray.UnitySArrayProxy.begin_iterator
MemoryError: std::bad_alloc
```

**Comment by znation** [comment] 2018-07-25 22:00
I think the issue here is that Turi Create lambda workers are incompatible with mxnet 1.2+. Hopefully this is something we can fix on our end. @shreyasvj25, is this tracked in another issue already? If not, let's use this issue to track it.

**Comment by shreyasvj25** [comment] 2018-07-25 22:12
As Zach mentioned, lambda workers are not compatible with mxnet 1.2+ on ubuntu.
@znation lets track this in #670

@THEDFG 
can you mitigate this issue by installing `mxnet-cu90==1.1.0` or `mxnet-cu91==1.1.0`  ?

If not, please follow this temporary workaround
`import turicreate as tc`
`tc.config.set_runtime_config('TURI_DEFAULT_NUM_PYLAMBDA_WORKERS', 1)`

**Comment by znation** [comment] 2018-07-25 22:16
Oh, I see, ultimately this is a dupe of #670.

**Closed by znation** 2018-07-25 22:16 UTC
Labels: bug, style transfer, workaround

**Comment by THEDFG** [comment] 2018-07-25 22:31
With 
tc.config.set_runtime_config('TURI_DEFAULT_NUM_PYLAMBDA_WORKERS', 1)
it works. Thanks

**Comment by THEDFG** [comment] 2018-07-25 23:05
#with tc.config.set_runtime_config('TURI_DEFAULT_NUM_PYLAMBDA_WORKERS', 1) crashed:

(venv) user@user:~/Desktop/turi/styleTransfer$ python styleTransfer.py 
WARNING: You are using MXNet 1.2.1 which may result in breaking behavior.
         To fix this, please install the currently recommended version:

             pip uninstall -y mxnet && pip install mxnet==1.1.0

         If you want to use a CUDA GPU, then change 'mxnet' to 'mxnet-cu90' (adjust 'cu90' depending on your CUDA version):

Read 262 images in 5.01257 secs speed: 52.2686 file/sec
Using 'image' in style_dataset as feature column and using 'image' in content_dataset as feature column
WARNING: You are using MXNet 1.2.1 which may result in breaking behavior.
         To fix this, please install the currently recommended version:

             pip uninstall -y mxnet && pip install mxnet==1.1.0

         If you want to use a CUDA GPU, then change 'mxnet' to 'mxnet-cu90' (adjust 'cu90' depending on your CUDA version):

Using default 1 lambda workers.
To maximize the degree of parallelism, add the following code to the beginning of the program:
"turicreate.config.set_runtime_config('TURI_DEFAULT_NUM_PYLAMBDA_WORKERS', 2)"
Note that increasing the degree of parallelism also increases the memory footprint.
/home/user/venv/local/lib/python2.7/site-packages/mxnet/gluon/block.py:413: UserWarning: load_params is deprecated. Please use load_parameters.
  warnings.warn("load_params is deprecated. Please use load_parameters.")
Using GPU to create model (CUDA)
Analyzing visual features of the style images
[01:14:51] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 122.691      | 244.0        |
| 21           | 77.697       | 254.4        |
| 42           | 66.804       | 264.6        |
| 54           | 56.338       | 777.4        |
| 74           | 54.532       | 787.8        |
| 95           | 60.637       | 798.1        |
| 107          | 47.432       | 919.0        |
| 127          | 68.314       | 929.1        |
| 148          | 54.079       | 939.4        |
| 159          | 62.185       | 954.8        |
| 160          | 65.101       | 1031.0       |
| 178          | 49.537       | 1041.1       |
| 199          | 40.611       | 1051.4       |
Traceback (most recent call last):
  File "styleTransfer.py", line 22, in <module>
    model = tc.style_transfer.create(styles, content, max_iterations=1000)
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/toolkits/style_transfer/style_transfer.py", line 287, in create
    for c_batch in content_images_loader:
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/toolkits/style_transfer/_sframe_loader.py", line 121, in next
    return self._next()
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/toolkits/style_transfer/_sframe_loader.py", line 145, in _next
    row = self.sframe[self.cur_sample]
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 3537, in __getitem__
    val_list = list(SFrame(_proxy = self.__proxy__.copy_range(lb, 1, ub)))
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 3666, in generator
    self.__proxy__.begin_iterator()
  File "turicreate/cython/cy_sframe.pyx", line 231, in turicreate.cython.cy_sframe.UnitySFrameProxy.begin_iterator
  File "turicreate/cython/cy_sframe.pyx", line 232, in turicreate.cython.cy_sframe.UnitySFrameProxy.begin_iterator
MemoryError: std::bad_alloc
[1]+  Killed

**Comment by shreyasvj25** [comment] 2018-07-25 23:40
Can you use cuda9.0 with mxnet-cu90==1.1.0 or cuda9.1 with mxnet-cu91==1.1.0?
If not, you may have to compile mxnet 1.1.0 for cuda9.2 for now
(https://mxnet.apache.org/install/ubuntu_setup.html)

**Comment by THEDFG** [comment] 2018-07-28 09:39
with mxnet-cu80 or mxnet-cu90 I get libinfo error:
(venv) user@user:~/Desktop/turi/styleTransfer$ pip freeze | grep mxnet
mxnet==1.1.0
mxnet-cu90==1.1.0
(venv) user@user:~/Desktop/turi/styleTransfer$ python styleTransfer.py
Read 64 images in 7.2944 secs speed: 8.77385 file/sec
Read 288 images in 21.5091 secs speed: 15.7584 file/sec
Read 309 images in 27.1677 secs speed: 3.71112 file/sec
Traceback (most recent call last):
  File "styleTransfer.py", line 24, in <module>
    model = tc.style_transfer.create(styles, content, max_iterations=5000, _advanced_parameters=params)
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/toolkits/style_transfer/style_transfer.py", line 115, in create
    from ._sframe_loader import SFrameSTIter as _SFrameSTIter
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/toolkits/style_transfer/_sframe_loader.py", line 11, in <module>
    import mxnet as _mx
  File "/home/user/venv/local/lib/python2.7/site-packages/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "/home/user/venv/local/lib/python2.7/site-packages/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "/home/user/venv/local/lib/python2.7/site-packages/mxnet/base.py", line 30, in <module>
    from . import libinfo
ImportError: cannot import name libinfo

**Comment by shreyasvj25** [comment] 2018-08-03 18:06
You need to downgrade cuda9.2 to cuda9.0 or cuda9.1.
As a workaround for mxnet-cuXX==1.2.1 on a linux gpu, can you try using: 
`import turicreate as tc`
`tc.config.set_runtime_config('TURI_DEFAULT_NUM_PYLAMBDA_WORKERS', 1)`
`tc.config.set_runtime_config('MXNET_CPU_WORKER_NTHREADS', 1)`

**Comment by THEDFG** [comment] 2018-08-13 17:28
MXNET_CPU_WORKER_NTHREADS is not recognized and if I comment this line with mxnet-cu91 I get: "ImportError: cannot import name libinfo"

(venv) user@user:~/Desktop/turi/styleTransfer$ pip freeze | grep mxnet
mxnet==1.2.1.post1
mxnet-cu91==1.2.1.post1
(venv) user@user:~/Desktop/turi/styleTransfer$ python styleTransfer.py 
Traceback (most recent call last):
  File "styleTransfer.py", line 12, in <module>
    tc.config.set_runtime_config('MXNET_CPU_WORKER_NTHREADS', 1)
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/config/__init__.py", line 304, in set_runtime_config
    raise RuntimeError(ret)
RuntimeError: No such configuration variable
(venv) user@user:~/Desktop/turi/styleTransfer$

**Comment by THEDFG** [comment] 2018-08-13 17:35
the same "ImportError: cannot import name libinfo" with mxnet-cu90

mxnet==1.2.1.post1
mxnet-cu90==1.2.1.post1
(venv) user@user:~/Desktop/turi/styleTransfer$ python styleTransfer.py Read 64 images in 6.69235 secs  speed: 9.56316 file/sec
Read 280 images in 13.1187 secs speed: 33.6114 file/sec
Traceback (most recent call last):
  File "styleTransfer.py", line 34, in <module>
    model = tc.style_transfer.create(styles, content, max_iterations=5000, _advanced_parameters=params)
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/toolkits/style_transfer/style_transfer.py", line 115, in create
    from ._sframe_loader import SFrameSTIter as _SFrameSTIter
  File "/home/user/venv/local/lib/python2.7/site-packages/turicreate/toolkits/style_transfer/_sframe_loader.py", line 11, in <module>
    import mxnet as _mx
  File "/home/user/venv/local/lib/python2.7/site-packages/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "/home/user/venv/local/lib/python2.7/site-packages/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "/home/user/venv/local/lib/python2.7/site-packages/mxnet/base.py", line 30, in <module>
    from . import libinfo
ImportError: cannot import name libinfo
(venv) user@user:~/Desktop/turi/styleTransfer$

**Comment by shreyasvj25** [comment] 2018-08-13 17:36
Set `MXNET_CPU_WORKER_NTHREADS` as an environment variable.
`import os`
`os.environ['MXNET_CPU_WORKER_NTHREADS'] = "1"`

But I see that now you are using mxnet-cu91==1.2.1
Can you uninstall both mxnet versions and 
`pip install mxnet-cu91==1.1.0` 
This should work fine without setting TURI_DEFAULT_NUM_PYLAMBDA_WORKERS and MXNET_CPU_WORKER_NTHREADS
