### ISSUE TITLE
Print and draw ROC_curve

### ISSUE THREAD

**Issue by kuri54** [apple/turicreate#1871] opened 2019-05-14 00:46 UTC
Python==3.6
Turi Create==5.5

model = tc.image_classifier.create(train_data)
metrics = model.evaluate(test_data)

print(metrics['accuracy']) -> 0.822
print(metrics['auc']) -> 0.906
print(metrics['roc_curve']) -> KeyError : ['roc_curve']

It had been done for a while.I can not do it for some reason.
ROC_curve can be drawn if this output can be done. Is there any other way?

**Comment by TobyRoseman** [comment] 2019-05-14 21:26
@kuri54 - Thanks for reporting this issue.

It looks like this is caused by #1335. The roc_curve is still calculated by logistic regression but [it is not being through](https://github.com/apple/turicreate/blob/752e0e4d88f692e4135031bd4673a8110b2ff783/src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py#L768).

We should get this fixed in the next release. If you can downgrade to `5.2.1`, you can get the ROC Curve.

**Comment by kuri54** [comment] 2019-05-14 23:19
Thanks！
Looking forward to Version 5.6.

**Comment by TobyRoseman** [comment] 2019-05-20 17:20
fixed via #1891

**Closed by TobyRoseman** 2019-05-20 17:20 UTC
Labels: bug, image classifier
