### ISSUE TITLE
export_coreml does not respect ~ in filenames (sound classifier).

### ISSUE THREAD

**Issue by hoytak** [apple/turicreate#2767] opened 2019-12-02 22:43 UTC
The following code: 

```
model.export_coreml("~/models/sc.mlmodel")
```

Will save the model file in a `<current directory>/\~/models/sc.mlmodel`.

**Comment by srikris** [comment] 2019-12-02 22:59
@hoytak Is this a regression from 5.8?

**Comment by TobyRoseman** [comment] 2019-12-03 19:25
> @hoytak Is this a regression from 5.8?

In 5.8 we get different behavior which is also wrong. It errors out: `FileNotFoundError: [Errno 2] No such file or directory: '~/models/sc.mlmodel'`. (`~/models` does exist; if I expand the `~`, it works.)

**Comment by jakesabathia2** [comment] 2020-01-02 09:13
@hoytak I tried your code:
```
model.export_coreml('~/Desktop/test.mlmodel')
```
and couldn't reproduce your error. Instead, it produced this kind of error like @TobyRoseman said:
```
IOError: [Errno 2] No such file or directory: '~/Desktop/test.mlmodel'
```
It seems like a coreml bug that it cannot recognize `~` in the path.
Any thought?

**Comment by hoytak** [comment] 2020-01-08 00:48
Yes, it depends on the write permissions of the current directory.  If it can't create \~/models, it will error out with a file not found error.  

Regardless, the correct behavior should be that ~/ is expanded universally when it's the first component in a file path.

**Comment by TobyRoseman** [comment] 2020-02-26 21:00
As far as I can tell we have this same issue with all of our toolkits, not just the sound classifier. I think it makes more sense to fix this issue in the coremltools package.

**Comment by TobyRoseman** [comment] 2020-02-26 21:38
[Pull request to fix this issue](https://github.com/apple/coremltools/pull/650) has been submitted to the coremltools.

**Comment by TobyRoseman** [comment] 2020-03-18 00:42
The fix for this issue has been merged into the coremltool repository. Once coremltools does a release we can depend on the new version and close this issue.

Since there is nothing more that can be done here in the current release, I'll remove this issue from the milestone.

**Closed** 2020-09-11 20:44 UTC
Labels: Core ML, bug, sound classifier
