### ISSUE TITLE
Killed upon reaching iteration limit

### ISSUE THREAD

**Issue by hipwelljo** [apple/turicreate#1075] opened 2018-09-08 15:13 UTC
Using Turi Create 5.0, I seem to be encountering the same issue #361 that others saw with a previous release. It completes training due to reaching the iteration limit, and then logs `Killed: 9`. It does not evaluate the model and log the accuracy.

```
model = tc.image_classifier.create(train_data, target='label', model='squeezenet_v1.1')

predictions = model.classify(test_data)

metrics = model.evaluate(test_data)
print "Accuracy: %s" % metrics['accuracy']
```

The output is:
```
Logistic regression:
--------------------------------------------------------
Number of examples          : 49264
Number of classes           : 5742
Number of feature columns   : 1
Number of unpacked features : 1000
Number of coefficients      : 5746741
Starting L-BFGS
--------------------------------------------------------
+-----------+----------+-----------+--------------+-------------------+---------------------+
| Iteration | Passes   | Step size | Elapsed Time | Training Accuracy | Validation Accuracy |
+-----------+----------+-----------+--------------+-------------------+---------------------+
| 0         | 1        | NaN       | 1410.938340  | 0.000142          | 0.000410            |
| 1         | 4        | 0.000101  | 6993.121902  | 0.000284          | 0.000000            |
| 2         | 6        | 1.000000  | 11684.099158 | 0.008038          | 0.002048            |
| 3         | 7        | 1.000000  | 14630.014436 | 0.056796          | 0.013923            |
| 4         | 8        | 1.000000  | 17736.467060 | 0.026713          | 0.005733            |
| 5         | 9        | 1.000000  | 20273.712870 | 0.072791          | 0.022113            |
| 6         | 10       | 1.000000  | 22618.025692 | 0.112049          | 0.037674            |
| 7         | 11       | 1.000000  | 25096.515562 | 0.178528          | 0.066339            |
| 8         | 12       | 1.000000  | 27513.523471 | 0.241698          | 0.088043            |
| 9         | 13       | 1.000000  | 29956.004078 | 0.290983          | 0.110156            |
| 10        | 14       | 1.000000  | 32559.100921 | 0.343476          | 0.139640            |
+-----------+----------+-----------+--------------+-------------------+---------------------+
Completed (Iteration limit reached).
This model may not be optimal. To improve it, consider increasing `max_iterations`.
Killed: 9
```

**Comment by srikris** [comment] 2018-09-08 16:37
Can you share the data by any chance. We can investigate what's going on.

**Comment by hipwelljo** [comment] 2018-09-09 00:14
I can't post it publicly, is there a way I can send it to you directly?

**Comment by srikris** [comment] 2019-01-10 15:44
@hipwelljo Can you confirm its fixed in the latest release.

**Comment by hipwelljo** [comment] 2019-01-11 04:48
It appears to be fixed. It has reached iteration 14 after 12 hours. I don't plan to let it finish. 😛

**Comment by TobyRoseman** [comment] 2019-01-11 19:37
@hipwelljo - thanks for the update. I'll close this issue but let us know if you have the problem again.

**Comment by TobyRoseman** [comment] 2019-01-11 22:38
Reopening since this issue only occurred at the end of training, probably when calculating validation set statistics.

**Comment by hipwelljo** [comment] 2019-01-13 02:14
Ok I set max_iterations to 10 and tried it again. It logged
```
Completed (Iteration limit reached).
This model may not be optimal. To improve it, consider increasing `max_iterations`.

```
and after a long while logged `Killed: 9` :(

As an aside it would be good to log what it's working on, like `Calculating validation set statistics` or whatever to not give the impression that it's fully completed as the previous line reads. :)

**Comment by srikris** [comment] 2019-01-17 21:18
We've identified the root cause and we have a plan to fix this. Milestone is set for 5.4. Thanks everyone!

**Comment by hoytak** [comment] 2019-02-21 22:02
We believe this was fixed with https://github.com/apple/turicreate/pull/1402.

**Comment by hoytak** [comment] 2019-03-14 17:23
In our internal tests, this has been resolved -- https://github.com/apple/turicreate/pull/1402 indeed seemed to fix the issue.  Please reopen if there are more issues after 5.4 is released.

**Closed by hoytak** 2019-03-14 17:23 UTC
Labels: bug, image classifier, p1, toolkits
