### ISSUE TITLE
Apending a _1 in the classes generated by xcode given a model name with '-'

### ISSUE THREAD

**Issue by josete89** [apple/turicreate#53] opened 2017-12-10 19:39 UTC
Hi

I've created a model using turicreate and I named 't-shirt_detector.mlmodel' and when I drag into xcode is generating a class called t_shirt_detector_1, which is crashing due to the initializer:
```
convenience init() {
        let bundle = Bundle(for: t_shirt_detector_1.self)
        let assetPath = bundle.url(forResource: "t_shirt_detector_1", withExtension:"mlmodelc")
        try! self.init(contentsOf: assetPath!)
    }
```

**Comment by gustavla** [comment] 2017-12-10 21:57
Thanks for trying out Turi Create and the object detector! I'm sorry that you are having this issue.

This has happened to me several times actually and I've been wondering if it's just me. The first time it happened, I also had a filename with a dash in it and assumed it might be related. Since then, it has also happened on filenames without a dash, so now I'm not so sure that is related. My work-around is to remove the model from Xcode, rename the file, and drag it into Xcode again.

I understand that this is not a very satisfactory solution, so I will leave this issue open and follow-up once I know more. Thanks @josete89 for letting us know!

**Comment by gustavla** [comment] 2017-12-18 22:43
I can confirm that this is indeed a bug relating to dashes in filenames (I must be misremembering that I saw this with a filename without a dash). A bug report has been filed and thanks again @josete89 for identifying this issue! I can consistently reproduce this issue.

I will leave this issue open, since even though this is not a bug specific to Turi Create, perhaps we should add a warning to the `export_coreml` functions if it discovers a dash in the output filename.

**Comment by znation** [comment] 2018-10-16 23:12
While the `_1` seems to still get appended, the crash appears to be fixed as of Xcode 10.

**Comment by znation** [comment] 2018-10-16 23:13
Closing since the remaining issue is purely on the Core ML side and is tracked separately.

**Closed by znation** 2018-10-16 23:13 UTC
Labels: Core ML, bug, p3
