### ISSUE TITLE
Support for Python 3.x

### ISSUE THREAD

**Issue by chengjun** [apple/turicreate#206] opened 2018-01-21 07:03 UTC
Recently, most python packages do not support python 2.7 anymore. And the python will officially stop support python 2.7 by within one more year. However, for quite a long time, GraphLab only support python 2.x. I am wondering whether it is possible for turi create to upgrade to python 3 now.

**Comment by srikris** [comment] 2018-01-21 18:33
Duplicate of #2. Python 3 support coming real soon! We are in the testing and validation phase.

**Closed by srikris** 2018-01-21 18:33 UTC
