### ISSUE TITLE
read_json: error tells to provide columns types but there is no such parameter

### ISSUE THREAD

**Issue by afranklin** [apple/turicreate#698] opened 2018-06-15 22:47 UTC
```
In [5]: sf = tc.SFrame.read_json('/Users/me/Downloads/annotations/image_info_test2014.json', orient="records")
Parsing JSON records from /Users/me/Downloads/annotations/image_info_test2014.json
Unable to parse /Users/tmuss/Downloads/annotations/image_info_test2014.json. It does not appear to be in JSON record format. A list of dictionaries is expected
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-ef243bc32856> in <module>()
----> 1 sf = tc.SFrame.read_json('/Users/me/Downloads/annotations/image_info_test2014.json', orient="records")

/Users/tmuss/venv/dev/lib/python2.7/site-packages/turicreate/data_structures/sframe.pyc in read_json(cls, url, orient)
   1710             g = SArray.from_json_records(url)
   1711             g = SFrame({'X1':g})
-> 1712             return g.unpack('X1','')
   1713         elif orient == "lines":
   1714             g = cls.read_csv(url, header=False)

/Users/me/venv/dev/lib/python2.7/site-packages/turicreate/data_structures/sframe.pyc in unpack(self, unpack_column, column_name_prefix, column_types, na_value, limit)
   5385             column_name_prefix = unpack_column
   5386
-> 5387         new_sf = self[unpack_column].unpack(column_name_prefix, column_types, na_value, limit)
   5388
   5389         # construct return SFrame, check if there is conflict

/Users/me/venv/dev/lib/python2.7/site-packages/turicreate/data_structures/sarray.pyc in unpack(self, column_name_prefix, column_types, na_value, limit)
   3258             lengths = [len(i) for i in head_rows]
   3259             if len(lengths) == 0 or max(lengths) == 0:
-> 3260                 raise RuntimeError("Cannot infer number of items from the SArray, SArray may be empty. please explicitly provide column types")
   3261
   3262             # infer column types for dict type at server side, for list and array, infer from client side

RuntimeError: Cannot infer number of items from the SArray, SArray may be empty. please explicitly provide column types
```

**Comment by afranklin** [comment] 2018-06-15 22:47
add parameter or update error message?

**Comment by znation** [comment] 2018-08-09 23:46
I think we should add the column_types parameter and it should probably behave the same way as with `read_csv`. @shantanuchhabra, do you mind taking this one?

**Comment by shantanuchhabra** [comment] 2018-08-10 18:37
I acquired the same JSON file that triggered this error and repro'ed this using Turi Create 5.0 beta 3. I got the following error (which doesn't mention anything about column types):

```
In [2]: sf = tc.SFrame.read_json('image_info_test2014.json')
Parsing JSON records from /Users/schhabra/Downloads/image_info_test2014.json
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-7cc26e872a18> in <module>()
----> 1 sf = tc.SFrame.read_json('image_info_test2014.json')

/Users/schhabra/Downloads/venv/lib/python2.7/site-packages/turicreate/data_structures/sframe.pyc in read_json(cls, url, orient)
   1559         """
   1560         if orient == "records":
-> 1561             g = SArray.read_json(url)
   1562             if len(g) == 0:
   1563                 return SFrame()

/Users/schhabra/Downloads/venv/lib/python2.7/site-packages/turicreate/data_structures/sarray.pyc in read_json(cls, filename)
    583         """
    584         proxy = UnitySArrayProxy()
--> 585         proxy.load_from_json_record_files(_make_internal_url(filename))
    586         return cls(_proxy = proxy)
    587 

turicreate/cython/cy_sarray.pyx in turicreate.cython.cy_sarray.UnitySArrayProxy.load_from_json_record_files()

turicreate/cython/cy_sarray.pyx in turicreate.cython.cy_sarray.UnitySArrayProxy.load_from_json_record_files()

RuntimeError: Unable to parse /Users/schhabra/Downloads/image_info_test2014.json. It does not appear to be in JSON record format. A list of dictionaries is expected
```

**Comment by shantanuchhabra** [comment] 2018-08-13 21:55
This error does not repro anymore. Closing this issue for now. We can create a new issue for adding `column_types` to `read_json` later if needed.

**Comment by srikris** [comment] 2018-08-13 21:59
@shantanuchhabra I think the issue is to update the error message right?

**Closed** 2018-08-13 22:00 UTC
Labels: SFrame, bug, p2
