### ISSUE TITLE
"Invalid PNG file" error on tc.Image(<path>) call

### ISSUE THREAD

**Issue by derekahc** [apple/turicreate#3032] opened 2020-03-05 19:36 UTC
Hello! Brand new to TC and ML in general here. 

I am following the steps in the Data Preparation article (https://github.com/apple/turicreate/blob/master/userguide/object_detection/data-preparation.md)

The process works great with the bikes + cars dataset provided! Now I am trying to create a model to recognize hands, with an awesome dataset found here (https://github.com/aurooj/Hand-Segmentation-in-the-Wild). 

I first ran into this when executing the 

```raw_sf = tc.image_analysis.load_images(ig02_path, recursive=True, random_order=True)```

step, but exists when I try to create a tc.Image as well. When running the ```image_analysis``` call, I get a series of ```Invalid PNG file``` errors like...

Invalid PNG file	 file: hands/hands/vid62675.image.png
Invalid PNG file	 file: hands/hands/vid63075.image.png
Invalid PNG file	 file: hands/hands/vid68115.image.png
Invalid PNG file	 file: hands/hands/vid42485.image.png

When trying to create a single tc.Image out of one of these files, I get the following trace...

>>> img = tc.Image('hands/hands/vid425.image.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<user>/.pyenv/versions/turi_tutorial/lib/python2.7/site-packages/turicreate/data_structures/image.py", line 68, in __init__
    img = _extensions.load_image(_make_internal_url(path), format)
  File "<user>/.pyenv/versions/turi_tutorial/lib/python2.7/site-packages/turicreate/extensions.py", line 181, in <lambda>
    return lambda *args, **kwargs: _run_toolkit_function(fn, arguments, args, kwargs)
  File "<user>/.pyenv/versions/turi_tutorial/lib/python2.7/site-packages/turicreate/extensions.py", line 169, in _run_toolkit_function
    raise _ToolkitError(ret[1])
turicreate.toolkits._main.ToolkitError: Invalid PNG file

I did a ```sips -g all vid425.image.png``` on one of the images to see if there's something weird with the png file and I get...

  pixelWidth: 224
  pixelHeight: 224
  typeIdentifier: public.jpeg
  format: jpeg
  formatOptions: default
  dpiWidth: 72.000
  dpiHeight: 72.000
  samplesPerPixel: 3
  bitsPerSample: 8
  hasAlpha: no
  space: RGB
  profile: Generic RGB Profile

I thought maybe the color profile could have something to do with it. Apart from the profile and the image size, this was identical to a ```sips``` of one of the car or bike images. However, removing the color profile didn't change the result, I still get the same Invalid PNG File error. 

Any help would be appreciated!

Thanks!

**Comment by TobyRoseman** [comment] 2020-03-05 21:09
It looks like there are two places in the code base that can generate that error message. Seems the cause is either [an invalid PNG signature](https://github.com/apple/turicreate/blob/5393ebbbdbc6e73e31724db0c4f39f5402d44af1/src/core/data/image/png_io.cpp#L91) or [a failure to parse the PNG header](https://github.com/apple/turicreate/blob/5393ebbbdbc6e73e31724db0c4f39f5402d44af1/src/core/data/image/png_io.cpp#L225).

We should probably have better (i.e. more specific) error messages in both of these cases.

**Comment by derekahc** [comment] 2020-03-05 23:15
I had done some manipulation of the filetypes (changing from jpg to png and whatnot). Perhaps something in this process corrupted the files. I started with some fresh images and everything seems to be working now.

**Comment by TobyRoseman** [comment] 2020-03-06 00:32
Thanks for letting us know. I'm going to close this issue, but let us know if you have any other issues.

**Closed by TobyRoseman** 2020-03-06 00:32 UTC
Labels: images
