### ISSUE TITLE
libbz2.so.1.0 missing?

### ISSUE THREAD

**Issue by guy4261** [apple/turicreate#2302] opened 2019-09-11 19:20 UTC
Since 5.7, I've been getting the following on my OracleLinux 6.9 (kinda like Centos) machines:
`ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory`.

`yum list installed | grep bz2` shows me that `bzip2-devel.x86_64` ([the relevant library](https://centos.pkgs.org/7/centos-x86_64/bzip2-devel-1.0.6-13.el7.x86_64.rpm.html)) is installed, yet this still happens.

Perhaps this is related to https://github.com/apple/turicreate/pull/2097 , which somehow made `libbz2` no longer statically compile with the rest of `turicreate`? (a tip I got from @hoytak!)

**Comment by dhivyaaxim** [comment] 2019-09-12 07:08
@guy4261  Install libbzz package and recompile it

sudo apt-get install libbz2-dev

**Comment by hoytak** [comment] 2020-01-03 22:31
This should be fixed with https://github.com/apple/turicreate/pull/2835.  A quick test shows that:

On OSX, `otool -L *.dylib | grep bz2` finds no dependency on bz2.  
On Linux, the same with ldd also finds no dependency on bz2. 

(In addition, it appears this was caused by installing libbz2-dev on some of the build machines, which is no longer the case.)

**Closed by hoytak** 2020-01-03 22:31 UTC
Labels: bug, build, infrastructure, p1, setup
