### ISSUE TITLE
Turicreate breaks Google Colab shell commands?

### ISSUE THREAD

**Issue by fbomb111** [apple/turicreate#1862] opened 2019-05-10 16:25 UTC
Steps to reproduce:

Open new Colab notebook on GPU

```
!ls #works
!pip install -q turicreate
import turicreate as tc
!ls #doesn't work
```

I get the following error:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-22-16fdbe588ee8> in <module>()
----> 1 get_ipython().system('ls')
      2 # !nvcc --version

2 frames
/usr/local/lib/python3.6/dist-packages/google/colab/_system_commands.py in _run_command(cmd, clear_streamed_output)
    165   if locale_encoding != _ENCODING:
    166     raise NotImplementedError(
--> 167         'A UTF-8 locale is required. Got {}'.format(locale_encoding))
    168 
    169   parent_pty, child_pty = pty.openpty()

NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968
```

I'm not certain what might be going on or how to work around it.  Thanks!

**Comment by TobyRoseman** [comment] 2019-05-10 20:32
I can reproduce this issue. It happens when using a GPU and when not using a GPU. It happens on both Python 2 and 3. I've also verified that it is not caused by any dependencies of TuriCreate; installing each one separately still allows you to run system commands.

This seems to be an issue with locale settings. [On start up turicreate sets the `LC_ALL` environment variable to `C`](https://github.com/apple/turicreate/blob/3a63741ba80af87af5c1546167f75761c59babbd/src/unity/python/turicreate/_sys_util.py#L76). For reason I don't understand this breaks Colab. Removing that environment variable seems to fix things.

As a temporary work around, please try the following:
```python
import turicreate as tc
import os
del os.environ['LC_ALL']
```

**Comment by fbomb111** [comment] 2019-05-11 03:24
This workaround resolved the `UTF-8` issue, thank you!

**Comment by hoytak** [comment] 2019-07-31 16:32
Resolved with https://github.com/apple/turicreate/pull/2174.

**Closed by hoytak** 2019-07-31 16:32 UTC
Labels: bug, engine, p3, workaround
