### ISSUE TITLE
Build dependencies on Centos 6 are partial

### ISSUE THREAD

**Issue by guy4261** [apple/turicreate#1669] opened 2019-03-26 11:30 UTC
The build instructions for Linux: https://github.com/apple/turicreate/blob/master/BUILD.md#build-dependencies

mention some,  but not all of the dependencies.

I build on a Docker image of `centos:6.9`, thus I begin with a very clean system, which I believe is the reason why I uncovered some unmentioned dependencies.

Since I'm on centos, I use the `scl` collections `devtoolset-7` and `python27` to get the build tools.

Apart from that, I installed the dependencies from the `BUILD.md` page - and still failed. It seems the following were missing:

* `git`  # as the build process git clones things,
* `patch`
* `rsync`
* `libpng` and `libpng-devel`

I use this script for my build

```bash
#!/bin/bash
# This was done in a docker container of centos 6.9 :
# First, click on the Docker icon in the top-right corner and choose Preferences.
# In the Advanced tab, raise the CPUs to 4, Memory to 8GB, and the Swap to 2GB.
# Then:
# docker run --init --rm -it centos:6.9
# In general I followed the official instructions from
# https://github.com/apple/turicreate/blob/master/LINUX_INSTALL.md#centos-6

yum install -y centos-release-scl
yum install -y python27
# https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/
yum install -y devtoolset-7

# https://stackoverflow.com/a/30365810/2064085
# Don't use `scl enable` which stops running the next commands in scripts where it's used.
for env in $(scl --list); do source "/opt/rh/${env}/enable"; done

python2.7 -c "import sys;assert sys.maxunicode == 1114111"
pip2.7 install --upgrade pip  # or just pip?

yum install -y blas lapack blas-devel lapack-devel wget nano git cmake patch

cd /
wget https://www.samba.org/ftp/ccache/ccache-3.5.1a.tar.gz
tar -xvf ccache-3.5.1a.tar.gz
cd ccache-3.5.1
./configure && make && make install
cd /

cd /
git clone https://github.com/ninja-build/ninja.git
cd ninja
./configure.py --bootstrap
export PATH=$(pwd):$PATH
export GENERATOR="-G Ninja"
cd /

# Assert pyfpe.h exists
file /opt/rh/python27/root/usr/include/python2.7/pyfpe.h

# gif_lib.h
yum install -y giflib-devel

# xxd
yum install -y vim-common

# zlib
yum install -y zlib zlib-devel

# visualization
yum install -y libpng libpng-devel
yum install -y rsync
yum install -y libX11-devel

REPO_DIR=/turicreate

if [[ ! -d "${REPO_DIR}" ]]; then

    mkdir -v -p "${REPO_DIR}"
    cd "${REPO_DIR}"
    git init

    git fetch --depth 1 https://github.com/apple/turicreate.git master:refs/remotes/origin/master
    git checkout master
    cd /
fi

cd "${REPO_DIR}"

# https://stackoverflow.com/a/48241814/2064085
# export PYTHON_INCLUDE_DIR=/usr/include/python2.7
# export PYTHON_LIBRARY=/usr/lib/python2.7/config/libpython2.7.so
./configure \
    -D PYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
    -D PYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))") \
    -D PYTHON_EXECUTABLE:FILEPATH=$(which python)

cd debug
ninja -j4
```

**Comment by znation** [comment] 2019-03-28 20:20
Thanks! I'll take this issue since I happen to have a related fix in progress for #1441.

**Comment by znation** [comment] 2019-05-14 01:48
Strange that you needed to install libpng -- that should be included in the turicreate repo (under deps/src). I'll investigate.

**Comment by znation** [comment] 2019-05-15 07:58
I wasn't able to repro needing to install libpng and libpng-devel (I can build successfully without those using the rest of the instructions above). I'm guessing you had some errors about missing libpng that were caused by an earlier (now fixed) issue with this setup, like an unsupported compiler version or something.

**Closed** 2019-05-16 06:31 UTC
Labels: build, docs, infrastructure, setup
